# Generated by Django 5.2.13 on 2026-04-11 22:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
        ('employees', '0012_manager_scope_indexes'),
        ('locations', '0001_initial'),
        ('organisations', '0008_billing_payment_invoice'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessPermission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=160, unique=True)),
                ('label', models.CharField(max_length=255)),
                ('domain', models.CharField(max_length=32)),
                ('resource', models.CharField(max_length=64)),
                ('action', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'access_permissions',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='AccessRole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=80, unique=True)),
                ('scope', models.CharField(choices=[('CONTROL_TOWER', 'Control Tower'), ('ORGANISATION', 'Organisation')], max_length=32)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_system', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'access_roles',
                'ordering': ['scope', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AccessRoleAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='access_role_assignments', to='organisations.organisation')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='access_control.accessrole')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_role_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'access_role_assignments',
                'ordering': ['role__scope', 'role__name', 'user__email'],
            },
        ),
        migrations.CreateModel(
            name='AccessRolePermission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='access_control.accesspermission')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='access_control.accessrole')),
            ],
            options={
                'db_table': 'access_role_permissions',
                'ordering': ['role__code', 'permission__code'],
            },
        ),
        migrations.AddField(
            model_name='accessrole',
            name='permissions',
            field=models.ManyToManyField(related_name='roles', through='access_control.AccessRolePermission', to='access_control.accesspermission'),
        ),
        migrations.CreateModel(
            name='AccessScope',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('scope_kind', models.CharField(choices=[('ALL_ORGANISATIONS', 'All organisations'), ('SELECTED_ORGANISATIONS', 'Selected organisations'), ('CURRENT_ORGANISATION', 'Current organisation'), ('ALL_EMPLOYEES', 'All employees'), ('OWN_RECORD', 'Own record'), ('REPORTING_TREE', 'Reporting tree'), ('SELECTED_DEPARTMENTS', 'Selected departments'), ('SELECTED_OFFICE_LOCATIONS', 'Selected office locations'), ('SELECTED_LEGAL_ENTITIES', 'Selected legal entities'), ('SELECTED_COST_CENTRES', 'Selected cost centres'), ('SELECTED_EMPLOYMENT_TYPES', 'Selected employment types'), ('SELECTED_GRADES', 'Selected grades'), ('SELECTED_BANDS', 'Selected bands'), ('SELECTED_DESIGNATIONS', 'Selected designations'), ('SELECTED_EMPLOYEES', 'Selected employees')], max_length=48)),
                ('value_text', models.CharField(blank=True, max_length=255)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scopes', to='access_control.accessroleassignment')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='departments.department')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='employees.employee')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('office_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='locations.officelocation')),
                ('organisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='organisations.organisation')),
            ],
            options={
                'db_table': 'access_scopes',
                'ordering': ['scope_kind', 'created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='accessroleassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('organisation__isnull', False)), fields=('user', 'role', 'organisation'), name='unique_org_access_role_assignment'),
        ),
        migrations.AddConstraint(
            model_name='accessroleassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('organisation__isnull', True)), fields=('user', 'role'), name='unique_ct_access_role_assignment'),
        ),
        migrations.AddConstraint(
            model_name='accessrolepermission',
            constraint=models.UniqueConstraint(fields=('role', 'permission'), name='unique_permission_per_access_role'),
        ),
    ]
