import datetime
import uuid

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('approvals', '0004_payroll_request_kinds_and_requester_user'),
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendancePolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('timezone_name', models.CharField(default='Asia/Kolkata', max_length=64)),
                ('default_start_time', models.TimeField(default=datetime.time(9, 0))),
                ('default_end_time', models.TimeField(default=datetime.time(18, 0))),
                ('grace_minutes', models.PositiveIntegerField(default=15)),
                ('full_day_min_minutes', models.PositiveIntegerField(default=480)),
                ('half_day_min_minutes', models.PositiveIntegerField(default=240)),
                ('overtime_after_minutes', models.PositiveIntegerField(default=540)),
                ('week_off_days', models.JSONField(blank=True, default=list)),
                ('allow_web_punch', models.BooleanField(default=True)),
                ('restrict_by_ip', models.BooleanField(default=False)),
                ('allowed_ip_ranges', models.JSONField(blank=True, default=list)),
                ('restrict_by_geo', models.BooleanField(default=False)),
                ('allowed_geo_sites', models.JSONField(blank=True, default=list)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.user')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.user')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_policies', to='organisations.organisation')),
            ],
            options={'db_table': 'attendance_policies', 'ordering': ['name']},
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('grace_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('full_day_min_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('half_day_min_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('overtime_after_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('is_overnight', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.user')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.user')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_shifts', to='organisations.organisation')),
            ],
            options={'db_table': 'attendance_shifts', 'ordering': ['name']},
        ),
        migrations.CreateModel(
            name='AttendanceSourceConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('kind', models.CharField(choices=[('API', 'API Source'), ('EXCEL', 'Excel Source'), ('DEVICE', 'Device Source')], max_length=24)),
                ('configuration', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('last_error', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.user')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.user')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_source_configs', to='organisations.organisation')),
            ],
            options={'db_table': 'attendance_source_configs', 'ordering': ['name']},
        ),
        migrations.CreateModel(
            name='ShiftAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.user')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_assignments', to='employees.employee')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.user')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_assignments', to='organisations.organisation')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='attendance.shift')),
            ],
            options={'db_table': 'attendance_shift_assignments', 'ordering': ['-start_date', 'employee__employee_code']},
        ),
        migrations.CreateModel(
            name='AttendancePunch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('action_type', models.CharField(choices=[('CHECK_IN', 'Check In'), ('CHECK_OUT', 'Check Out'), ('RAW', 'Raw Punch')], default='RAW', max_length=16)),
                ('source', models.CharField(choices=[('WEB', 'Web'), ('IMPORT', 'Excel Import'), ('API', 'External API'), ('REGULARIZATION', 'Regularization'), ('MANUAL', 'Manual')], default='WEB', max_length=24)),
                ('punch_at', models.DateTimeField()),
                ('remote_ip', models.CharField(blank=True, max_length=64)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.user')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_punches', to='employees.employee')),
                ('import_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='punches', to='attendance.attendanceimportjob')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.user')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_punches', to='organisations.organisation')),
                ('source_config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='punches', to='attendance.attendancesourceconfig')),
            ],
            options={'db_table': 'attendance_punches', 'ordering': ['-punch_at']},
        ),
        migrations.CreateModel(
            name='AttendanceDay',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('attendance_date', models.DateField()),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('HALF_DAY', 'Half Day'), ('ABSENT', 'Absent'), ('INCOMPLETE', 'Incomplete'), ('HOLIDAY', 'Holiday'), ('WEEK_OFF', 'Week Off'), ('ON_LEAVE', 'On Leave'), ('ON_DUTY', 'On Duty')], default='ABSENT', max_length=24)),
                ('source', models.CharField(blank=True, default='', max_length=24)),
                ('check_in_at', models.DateTimeField(blank=True, null=True)),
                ('check_out_at', models.DateTimeField(blank=True, null=True)),
                ('worked_minutes', models.PositiveIntegerField(default=0)),
                ('overtime_minutes', models.PositiveIntegerField(default=0)),
                ('late_minutes', models.PositiveIntegerField(default=0)),
                ('paid_fraction', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('leave_fraction', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('on_duty_fraction', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('is_holiday', models.BooleanField(default=False)),
                ('is_week_off', models.BooleanField(default=False)),
                ('is_late', models.BooleanField(default=False)),
                ('needs_regularization', models.BooleanField(default=False)),
                ('raw_punch_count', models.PositiveIntegerField(default=0)),
                ('note', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.user')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_days', to='employees.employee')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.user')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_days', to='organisations.organisation')),
                ('policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_days', to='attendance.attendancepolicy')),
                ('shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_days', to='attendance.shift')),
            ],
            options={'db_table': 'attendance_days', 'ordering': ['-attendance_date', 'employee__employee_code']},
        ),
        migrations.CreateModel(
            name='AttendanceRegularizationRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('attendance_date', models.DateField()),
                ('requested_check_in_at', models.DateTimeField(blank=True, null=True)),
                ('requested_check_out_at', models.DateTimeField(blank=True, null=True)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled'), ('WITHDRAWN', 'Withdrawn')], default='PENDING', max_length=24)),
                ('rejection_reason', models.TextField(blank=True)),
                ('approval_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_regularization_requests', to='approvals.approvalrun')),
                ('attendance_day', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='regularization_requests', to='attendance.attendanceday')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.user')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_regularization_requests', to='employees.employee')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.user')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_regularization_requests', to='organisations.organisation')),
            ],
            options={'db_table': 'attendance_regularization_requests', 'ordering': ['-created_at']},
        ),
        migrations.AddConstraint(
            model_name='attendancepolicy',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('organisation',), name='unique_default_attendance_policy_per_org'),
        ),
        migrations.AddConstraint(
            model_name='attendanceday',
            constraint=models.UniqueConstraint(fields=('organisation', 'employee', 'attendance_date'), name='unique_attendance_day_per_employee_date'),
        ),
        migrations.AddIndex(
            model_name='shiftassignment',
            index=models.Index(fields=['organisation', 'employee', 'start_date'], name='attendance_s_organis_9ec2f0_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancepunch',
            index=models.Index(fields=['organisation', 'punch_at'], name='attendance_p_organis_0ac80a_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancepunch',
            index=models.Index(fields=['employee', 'punch_at'], name='attendance_p_employe_5a4d24_idx'),
        ),
        migrations.AddIndex(
            model_name='attendanceday',
            index=models.Index(fields=['organisation', 'attendance_date', 'status'], name='attendance_d_organis_8bc7f2_idx'),
        ),
        migrations.AddIndex(
            model_name='attendanceday',
            index=models.Index(fields=['employee', 'attendance_date'], name='attendance_d_employe_56b860_idx'),
        ),
        migrations.AddIndex(
            model_name='attendanceregularizationrequest',
            index=models.Index(fields=['organisation', 'status'], name='attendance_r_organis_8f66c0_idx'),
        ),
        migrations.AddIndex(
            model_name='attendanceregularizationrequest',
            index=models.Index(fields=['employee', 'attendance_date'], name='attendance_r_employe_c91f9f_idx'),
        ),
    ]
