# Generated by Django 4.2.16 on 2026-04-06 20:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0005_organisationlicencebatch_invoice_reference_and_more'),
        ('employees', '0005_employeeprofile_statutory_ids'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('attendance', '0003_biometric_device_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceOvertimeApproval',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('approved_minutes', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('rejection_reason', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'attendance_overtime_approvals',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShiftRotationAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'attendance_shift_rotation_assignments',
                'ordering': ['-start_date', 'employee__employee_code'],
            },
        ),
        migrations.CreateModel(
            name='ShiftRotationTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('rotation_interval_days', models.PositiveIntegerField(default=7)),
                ('shift_sequence', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'attendance_shift_rotation_templates',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WFHRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('session', models.CharField(choices=[('FULL_DAY', 'Full Day'), ('FIRST_HALF', 'First Half'), ('SECOND_HALF', 'Second Half')], default='FULL_DAY', max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled'), ('WITHDRAWN', 'Withdrawn')], default='PENDING', max_length=20)),
                ('rejection_reason', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'attendance_wfh_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='attendanceday',
            new_name='attendance__organis_775899_idx',
            old_name='attendance_d_organis_8bc7f2_idx',
        ),
        migrations.RenameIndex(
            model_name='attendanceday',
            new_name='attendance__employe_f7e31f_idx',
            old_name='attendance_d_employe_56b860_idx',
        ),
        migrations.RenameIndex(
            model_name='attendanceimportjob',
            new_name='attendance__organis_67ae81_idx',
            old_name='attendance_i_organis_1bc4ba_idx',
        ),
        migrations.RenameIndex(
            model_name='attendanceimportjob',
            new_name='attendance__organis_768aa1_idx',
            old_name='attendance_i_organis_3f1e3e_idx',
        ),
        migrations.RenameIndex(
            model_name='attendanceimportrow',
            new_name='attendance__job_id_08443f_idx',
            old_name='attendance_i_job_id_31e37b_idx',
        ),
        migrations.RenameIndex(
            model_name='attendanceimportrow',
            new_name='attendance__employe_fa1b45_idx',
            old_name='attendance_i_employe_2c24b9_idx',
        ),
        migrations.RenameIndex(
            model_name='attendancepunch',
            new_name='attendance__organis_ae12f8_idx',
            old_name='attendance_p_organis_0ac80a_idx',
        ),
        migrations.RenameIndex(
            model_name='attendancepunch',
            new_name='attendance__employe_59e904_idx',
            old_name='attendance_p_employe_5a4d24_idx',
        ),
        migrations.RenameIndex(
            model_name='attendancerecord',
            new_name='attendance__organis_0108a0_idx',
            old_name='attendance_r_organis_f7f67e_idx',
        ),
        migrations.RenameIndex(
            model_name='attendancerecord',
            new_name='attendance__employe_31915a_idx',
            old_name='attendance_r_employe_29a743_idx',
        ),
        migrations.RenameIndex(
            model_name='attendanceregularizationrequest',
            new_name='attendance__organis_a56b3e_idx',
            old_name='attendance_r_organis_8f66c0_idx',
        ),
        migrations.RenameIndex(
            model_name='attendanceregularizationrequest',
            new_name='attendance__employe_b84f0b_idx',
            old_name='attendance_r_employe_c91f9f_idx',
        ),
        migrations.RenameIndex(
            model_name='shiftassignment',
            new_name='attendance__organis_251cc8_idx',
            old_name='attendance_s_organis_9ec2f0_idx',
        ),
        migrations.AddField(
            model_name='attendancepolicy',
            name='overtime_approval_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendancepolicy',
            name='overtime_max_payable_minutes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendancepolicy',
            name='overtime_multiplier',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=6),
        ),
        migrations.AddField(
            model_name='attendancepolicy',
            name='overtime_threshold_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='attendanceday',
            name='status',
            field=models.CharField(choices=[('PRESENT', 'Present'), ('HALF_DAY', 'Half Day'), ('ABSENT', 'Absent'), ('INCOMPLETE', 'Incomplete'), ('HOLIDAY', 'Holiday'), ('WEEK_OFF', 'Week Off'), ('ON_LEAVE', 'On Leave'), ('ON_DUTY', 'On Duty'), ('WFH', 'Work From Home')], default='ABSENT', max_length=24),
        ),
        migrations.AddField(
            model_name='wfhrequest',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='wfhrequest',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wfh_requests', to='employees.employee'),
        ),
        migrations.AddField(
            model_name='wfhrequest',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shiftrotationtemplate',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shiftrotationtemplate',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shiftrotationtemplate',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_rotation_templates', to='organisations.organisation'),
        ),
        migrations.AddField(
            model_name='shiftrotationassignment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shiftrotationassignment',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_rotation_assignments', to='employees.employee'),
        ),
        migrations.AddField(
            model_name='shiftrotationassignment',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shiftrotationassignment',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_rotation_assignments', to='organisations.organisation'),
        ),
        migrations.AddField(
            model_name='shiftrotationassignment',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='attendance.shiftrotationtemplate'),
        ),
        migrations.AddField(
            model_name='attendanceovertimeapproval',
            name='attendance_day',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='overtime_approval', to='attendance.attendanceday'),
        ),
        migrations.AddField(
            model_name='attendanceovertimeapproval',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attendanceovertimeapproval',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_overtime_approvals', to='employees.employee'),
        ),
        migrations.AddField(
            model_name='attendanceovertimeapproval',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='wfhrequest',
            index=models.Index(fields=['employee', 'status'], name='attendance__employe_0bbbc7_idx'),
        ),
        migrations.AddIndex(
            model_name='wfhrequest',
            index=models.Index(fields=['employee', 'start_date', 'end_date'], name='attendance__employe_76763f_idx'),
        ),
        migrations.AddIndex(
            model_name='shiftrotationassignment',
            index=models.Index(fields=['organisation', 'employee', 'start_date'], name='attendance__organis_43c713_idx'),
        ),
        migrations.AddIndex(
            model_name='attendanceovertimeapproval',
            index=models.Index(fields=['employee', 'status'], name='attendance__employe_9237ad_idx'),
        ),
    ]
