# Generated by Django 4.2.16 on 2026-04-07 12:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organisations', '0007_rename_tenant_data_organis_d368f1_idx_tenant_data_organis_42bc8e_idx_and_more'),
        ('locations', '0001_initial'),
        ('attendance', '0004_attendanceovertimeapproval_shiftrotationassignment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendanceday',
            name='source',
            field=models.CharField(blank=True, choices=[('WEB', 'Web'), ('IMPORT', 'Excel Import'), ('API', 'External API'), ('DEVICE', 'Biometric Device'), ('REGULARIZATION', 'Regularization'), ('MANUAL', 'Manual'), ('MOBILE', 'Mobile App')], default='', max_length=24),
        ),
        migrations.AlterField(
            model_name='attendancepunch',
            name='source',
            field=models.CharField(choices=[('WEB', 'Web'), ('IMPORT', 'Excel Import'), ('API', 'External API'), ('DEVICE', 'Biometric Device'), ('REGULARIZATION', 'Regularization'), ('MANUAL', 'Manual'), ('MOBILE', 'Mobile App')], default='WEB', max_length=24),
        ),
        migrations.CreateModel(
            name='GeoFencePolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(decimal_places=6, help_text='Centre latitude of the geo-fence', max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, help_text='Centre longitude of the geo-fence', max_digits=9)),
                ('radius_metres', models.PositiveIntegerField(default=100, help_text='Allowed radius in metres from the centre point')),
                ('enforcement_mode', models.CharField(choices=[('WARN', 'Warn Only'), ('BLOCK', 'Block')], default='WARN', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geo_fence_policies', to='locations.officelocation')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geo_fence_policies', to='organisations.organisation')),
            ],
            options={
                'db_table': 'attendance_geo_fence_policies',
                'ordering': ['name'],
            },
        ),
        migrations.AddConstraint(
            model_name='geofencepolicy',
            constraint=models.UniqueConstraint(fields=('organisation', 'location'), name='unique_geo_fence_per_location'),
        ),
    ]
