# Generated by Django 4.2.16 on 2026-03-28 16:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Payment'), ('PAID', 'Paid'), ('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended')], default='PENDING', max_length=20)),
                ('licence_count', models.PositiveIntegerField(default=0)),
                ('address', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('logo_url', models.URLField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_organisations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'organisations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrganisationStateTransition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_status', models.CharField(choices=[('PENDING', 'Pending Payment'), ('PAID', 'Paid'), ('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended')], max_length=20)),
                ('to_status', models.CharField(choices=[('PENDING', 'Pending Payment'), ('PAID', 'Paid'), ('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended')], max_length=20)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state_transitions', to='organisations.organisation')),
                ('transitioned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='org_transitions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'organisation_state_transitions',
                'ordering': ['-created_at'],
            },
        ),
    ]
