# Generated by Django 4.2.16 on 2026-03-30 20:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organisations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='access_state',
            field=models.CharField(choices=[('PROVISIONING', 'Provisioning'), ('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended')], default='PROVISIONING', max_length=20),
        ),
        migrations.AddField(
            model_name='organisation',
            name='activated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organisation',
            name='billing_status',
            field=models.CharField(choices=[('PENDING_PAYMENT', 'Pending Payment'), ('PAID', 'Paid')], default='PENDING_PAYMENT', max_length=24),
        ),
        migrations.AddField(
            model_name='organisation',
            name='country_code',
            field=models.CharField(default='IN', max_length=2),
        ),
        migrations.AddField(
            model_name='organisation',
            name='currency',
            field=models.CharField(default='INR', max_length=3),
        ),
        migrations.AddField(
            model_name='organisation',
            name='onboarding_stage',
            field=models.CharField(choices=[('ORG_CREATED', 'Organisation Created'), ('LICENCES_ASSIGNED', 'Licences Assigned'), ('PAYMENT_CONFIRMED', 'Payment Confirmed'), ('ADMIN_INVITED', 'Admin Invited'), ('ADMIN_ACTIVATED', 'Admin Activated'), ('MASTER_DATA_CONFIGURED', 'Master Data Configured'), ('EMPLOYEES_INVITED', 'Employees Invited')], default='ORG_CREATED', max_length=32),
        ),
        migrations.AddField(
            model_name='organisation',
            name='paid_marked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organisation',
            name='paid_marked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paid_organisations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organisation',
            name='primary_admin_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_admin_organisations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organisation',
            name='suspended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='OrganisationLifecycleEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('ORGANISATION_CREATED', 'Organisation Created'), ('LICENCES_UPDATED', 'Licences Updated'), ('PAYMENT_MARKED', 'Payment Marked'), ('ADMIN_INVITED', 'Admin Invited'), ('ADMIN_ACTIVATED', 'Admin Activated'), ('ACCESS_SUSPENDED', 'Access Suspended'), ('ACCESS_RESTORED', 'Access Restored'), ('MASTER_DATA_CONFIGURED', 'Master Data Configured'), ('EMPLOYEE_INVITED', 'Employee Invited')], max_length=32)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organisation_lifecycle_events', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lifecycle_events', to='organisations.organisation')),
            ],
            options={
                'db_table': 'organisation_lifecycle_events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrganisationLicenceLedger',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('delta', models.IntegerField()),
                ('reason', models.CharField(choices=[('OPENING_BALANCE', 'Opening Balance'), ('PURCHASE', 'Purchase'), ('ADJUSTMENT', 'Adjustment'), ('CORRECTION', 'Correction')], max_length=24)),
                ('note', models.TextField(blank=True)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='licence_ledger_entries', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licence_ledger_entries', to='organisations.organisation')),
            ],
            options={
                'db_table': 'organisation_licence_ledger',
                'ordering': ['-created_at'],
            },
        ),
    ]
