# Generated by Django 4.2.16 on 2026-03-31 06:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


def backfill_org_admin_memberships(apps, schema_editor):
    User = apps.get_model('accounts', 'User')
    OrganisationMembership = apps.get_model('organisations', 'OrganisationMembership')

    for user in User.objects.exclude(organisation_id=None).filter(role='ORG_ADMIN'):
        OrganisationMembership.objects.update_or_create(
            user_id=user.id,
            organisation_id=user.organisation_id,
            defaults={
                'is_org_admin': True,
                'status': 'ACTIVE' if user.is_active else 'INVITED',
                'accepted_at': user.created_at if user.is_active else None,
            },
        )


def remove_backfilled_org_admin_memberships(apps, schema_editor):
    OrganisationMembership = apps.get_model('organisations', 'OrganisationMembership')
    OrganisationMembership.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0004_user_account_type_alter_user_email_and_more'),
        ('organisations', '0002_organisation_access_state_organisation_activated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganisationMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_org_admin', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('INVITED', 'Invited'), ('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('REVOKED', 'Revoked')], default='INVITED', max_length=20)),
                ('invited_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_memberships', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='organisations.organisation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organisation_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'organisation_memberships',
                'ordering': ['organisation__name', 'user__email'],
            },
        ),
        migrations.AddConstraint(
            model_name='organisationmembership',
            constraint=models.UniqueConstraint(fields=('user', 'organisation'), name='unique_user_membership_per_organisation'),
        ),
        migrations.RunPython(backfill_org_admin_memberships, remove_backfilled_org_admin_memberships),
    ]
