# Generated by Django 4.2.16 on 2026-03-31 20:34

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0004_organisationlicencebatch'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='pan_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='OrganisationAddress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('address_type', models.CharField(choices=[('REGISTERED', 'Registered'), ('BILLING', 'Billing'), ('HEADQUARTERS', 'Headquarters'), ('WAREHOUSE', 'Warehouse'), ('CUSTOM', 'Custom')], max_length=24)),
                ('label', models.CharField(blank=True, max_length=255)),
                ('line1', models.TextField()),
                ('line2', models.TextField(blank=True)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(default='India', max_length=100)),
                ('pincode', models.CharField(max_length=20)),
                ('gstin', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='organisations.organisation')),
            ],
            options={
                'db_table': 'organisation_addresses',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='organisationaddress',
            constraint=models.UniqueConstraint(condition=models.Q(('address_type', 'REGISTERED'), ('is_active', True)), fields=('organisation', 'address_type'), name='unique_active_registered_address_per_org'),
        ),
        migrations.AddConstraint(
            model_name='organisationaddress',
            constraint=models.UniqueConstraint(condition=models.Q(('address_type', 'BILLING'), ('is_active', True)), fields=('organisation', 'address_type'), name='unique_active_billing_address_per_org'),
        ),
    ]
