# Generated by Django 4.2.16 on 2026-04-06 20:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organisations', '0004_organisationfeatureflag'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisationlicencebatch',
            name='invoice_reference',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='organisationlicencebatch',
            name='payment_provider',
            field=models.CharField(choices=[('MANUAL', 'Manual'), ('RAZORPAY', 'Razorpay')], default='MANUAL', max_length=20),
        ),
        migrations.AddField(
            model_name='organisationlicencebatch',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='organisationlifecycleevent',
            name='event_type',
            field=models.CharField(choices=[('ORGANISATION_CREATED', 'Organisation Created'), ('LICENCES_UPDATED', 'Licences Updated'), ('PAYMENT_MARKED', 'Payment Marked'), ('ADMIN_INVITED', 'Admin Invited'), ('ADMIN_ACTIVATED', 'Admin Activated'), ('ACCESS_SUSPENDED', 'Access Suspended'), ('ACCESS_RESTORED', 'Access Restored'), ('MASTER_DATA_CONFIGURED', 'Master Data Configured'), ('EMPLOYEE_INVITED', 'Employee Invited'), ('ACT_AS_STARTED', 'Act As Started'), ('ACT_AS_REFRESHED', 'Act As Refreshed'), ('ACT_AS_STOPPED', 'Act As Stopped')], max_length=32),
        ),
        migrations.CreateModel(
            name='OrgUsageStat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('snapshot_date', models.DateField()),
                ('active_employees', models.PositiveIntegerField(default=0)),
                ('active_users', models.PositiveIntegerField(default=0)),
                ('attendance_days_count', models.PositiveIntegerField(default=0)),
                ('leave_requests_count', models.PositiveIntegerField(default=0)),
                ('payroll_runs_count', models.PositiveIntegerField(default=0)),
                ('pending_approvals_count', models.PositiveIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_stats', to='organisations.organisation')),
            ],
            options={
                'db_table': 'organisation_usage_stats',
                'ordering': ['-snapshot_date', 'organisation__name'],
            },
        ),
        migrations.CreateModel(
            name='OrganisationBillingEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(choices=[('MANUAL', 'Manual'), ('RAZORPAY', 'Razorpay')], max_length=20)),
                ('event_type', models.CharField(max_length=100)),
                ('provider_event_id', models.CharField(max_length=255, unique=True)),
                ('provider_payment_id', models.CharField(blank=True, max_length=255)),
                ('invoice_reference', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('RECEIVED', 'Received'), ('PROCESSED', 'Processed'), ('IGNORED', 'Ignored'), ('FAILED', 'Failed')], default='RECEIVED', max_length=20)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('failure_reason', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('licence_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_events', to='organisations.organisationlicencebatch')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_events', to='organisations.organisation')),
            ],
            options={
                'db_table': 'organisation_billing_events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OnboardingChecklist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('step', models.CharField(choices=[('ADMINS', 'Admin Users'), ('DEPARTMENTS', 'Departments'), ('LOCATIONS', 'Locations'), ('LEAVE', 'Leave Configuration'), ('PAYROLL', 'Payroll Configuration'), ('POLICIES', 'Attendance Policies'), ('HOLIDAYS', 'Holiday Calendar'), ('FIRST_EMPLOYEE', 'First Employee Invite')], max_length=30)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_checklist', to='organisations.organisation')),
            ],
            options={
                'db_table': 'organisation_onboarding_checklist',
            },
        ),
        migrations.AddConstraint(
            model_name='orgusagestat',
            constraint=models.UniqueConstraint(fields=('organisation', 'snapshot_date'), name='unique_usage_stat_per_org_date'),
        ),
        migrations.AddIndex(
            model_name='organisationbillingevent',
            index=models.Index(fields=['organisation', 'provider', 'status'], name='organisatio_organis_ecf3b9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='onboardingchecklist',
            unique_together={('organisation', 'step')},
        ),
    ]
