# Generated by Django 4.2.16 on 2026-04-07 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organisations', '0005_organisationlicencebatch_invoice_reference_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantDataExportBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('export_type', models.CharField(choices=[('EMPLOYEES', 'Employees'), ('PAYSLIPS', 'Payslips'), ('LEAVE_HISTORY', 'Leave History'), ('AUDIT_LOG', 'Audit Log')], max_length=20)),
                ('status', models.CharField(choices=[('REQUESTED', 'Requested'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='REQUESTED', max_length=20)),
                ('artifact_key', models.CharField(blank=True, max_length=500)),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('content_type', models.CharField(blank=True, max_length=120)),
                ('file_size_bytes', models.PositiveIntegerField(default=0)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('failure_reason', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_data_exports', to='organisations.organisation')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_tenant_data_exports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tenant_data_export_batches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='tenantdataexportbatch',
            index=models.Index(fields=['organisation', 'status'], name='tenant_data_organis_d368f1_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantdataexportbatch',
            index=models.Index(fields=['organisation', 'export_type'], name='tenant_data_organis_31c5de_idx'),
        ),
    ]
