# Generated by Codex on 2026-04-01

import uuid

from django.db import migrations


def _safe_line1(value, fallback):
    return (value or '').strip() or fallback


def _safe_city(value):
    return (value or '').strip() or 'Unknown'


def _safe_state(value):
    return (value or '').strip() or 'Unknown'


def _safe_country(value):
    return (value or '').strip() or 'India'


def _safe_pincode(value):
    return (value or '').strip() or '000000'


def backfill_addresses_and_locations(apps, schema_editor):
    Organisation = apps.get_model('organisations', 'Organisation')
    OrganisationAddress = apps.get_model('organisations', 'OrganisationAddress')
    OfficeLocation = apps.get_model('locations', 'OfficeLocation')

    for organisation in Organisation.objects.all().iterator():
        registered = OrganisationAddress.objects.filter(
            organisation=organisation,
            address_type='REGISTERED',
            is_active=True,
        ).first()
        billing = OrganisationAddress.objects.filter(
            organisation=organisation,
            address_type='BILLING',
            is_active=True,
        ).first()

        legacy_line1 = _safe_line1(organisation.address, f'{organisation.name} Registered Office')

        if registered is None:
            registered = OrganisationAddress.objects.create(
                id=uuid.uuid4(),
                organisation=organisation,
                address_type='REGISTERED',
                label='Registered Office',
                line1=legacy_line1,
                city='Unknown',
                state='Unknown',
                country='India',
                pincode='000000',
                is_active=True,
            )

        if billing is None:
            billing = OrganisationAddress.objects.create(
                id=uuid.uuid4(),
                organisation=organisation,
                address_type='BILLING',
                label='Billing Address',
                line1=legacy_line1,
                city='Unknown',
                state='Unknown',
                country='India',
                pincode='000000',
                is_active=True,
            )

        locations = list(OfficeLocation.objects.filter(organisation=organisation).iterator())
        if not locations:
            for address in (registered, billing):
                OfficeLocation.objects.create(
                    id=uuid.uuid4(),
                    organisation=organisation,
                    organisation_address=address,
                    name=address.label,
                    address=address.line1,
                    city=address.city,
                    state=address.state,
                    country=address.country,
                    pincode=address.pincode,
                    is_active=True,
                    is_remote=False,
                )
            continue

        for location in locations:
            if location.organisation_address_id:
                continue

            matched_address = OrganisationAddress.objects.filter(
                organisation=organisation,
                line1=location.address.strip() or registered.line1,
                city=_safe_city(location.city),
                state=_safe_state(location.state),
                country=_safe_country(location.country),
                pincode=_safe_pincode(location.pincode),
            ).first()

            if matched_address is None:
                matched_address = OrganisationAddress.objects.create(
                    id=uuid.uuid4(),
                    organisation=organisation,
                    address_type='CUSTOM',
                    label=location.name,
                    line1=_safe_line1(location.address, location.name),
                    city=_safe_city(location.city),
                    state=_safe_state(location.state),
                    country=_safe_country(location.country),
                    pincode=_safe_pincode(location.pincode),
                    is_active=True,
                )

            location.organisation_address = matched_address
            location.address = matched_address.line1
            location.city = matched_address.city
            location.state = matched_address.state
            location.country = matched_address.country
            location.pincode = matched_address.pincode
            location.save(
                update_fields=[
                    'organisation_address',
                    'address',
                    'city',
                    'state',
                    'country',
                    'pincode',
                    'updated_at',
                ]
            )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0005_organisation_pan_number_organisationaddress_and_more'),
        ('locations', '0002_officelocation_is_remote_and_more'),
    ]

    operations = [
        migrations.RunPython(backfill_addresses_and_locations, noop_reverse),
    ]
