# Generated by Django 4.2.16 on 2026-04-07 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0006_tenantdataexportbatch'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='tenantdataexportbatch',
            new_name='tenant_data_organis_42bc8e_idx',
            old_name='tenant_data_organis_d368f1_idx',
        ),
        migrations.RenameIndex(
            model_name='tenantdataexportbatch',
            new_name='tenant_data_organis_478548_idx',
            old_name='tenant_data_organis_31c5de_idx',
        ),
        migrations.AddField(
            model_name='organisation',
            name='esi_branch_code',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
