# Generated by Codex on 2026-04-01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0006_backfill_addresses_and_locations'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='entity_type',
            field=models.CharField(
                choices=[
                    ('PRIVATE_LIMITED', 'Private Limited Company'),
                    ('PUBLIC_LIMITED', 'Public Limited Company'),
                    ('LIMITED_LIABILITY_PARTNERSHIP', 'Limited Liability Partnership'),
                    ('PARTNERSHIP_FIRM', 'Partnership Firm'),
                    ('SOLE_PROPRIETORSHIP', 'Sole Proprietorship'),
                    ('ONE_PERSON_COMPANY', 'One Person Company'),
                    ('SECTION_8_COMPANY', 'Section 8 Company'),
                    ('TRUST', 'Trust'),
                    ('SOCIETY', 'Society'),
                    ('GOVERNMENT_BODY', 'Government Body'),
                    ('OTHER', 'Other'),
                ],
                default='PRIVATE_LIMITED',
                max_length=40,
            ),
        ),
    ]
