# Generated by Codex on 2026-04-01

from django.db import migrations, models


def backfill_organisation_address_country_codes(apps, schema_editor):
    OrganisationAddress = apps.get_model('organisations', 'OrganisationAddress')
    for address in OrganisationAddress.objects.select_related('organisation').all():
        updates = []
        target_country_code = getattr(address.organisation, 'country_code', None) or 'IN'
        if not address.country_code:
            address.country_code = target_country_code
            updates.append('country_code')
        if address.state_code is None:
            address.state_code = ''
            updates.append('state_code')
        if updates:
            address.save(update_fields=updates)


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0007_organisation_entity_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisationaddress',
            name='country_code',
            field=models.CharField(default='IN', max_length=2),
        ),
        migrations.AddField(
            model_name='organisationaddress',
            name='state_code',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.RunPython(backfill_organisation_address_country_codes, migrations.RunPython.noop),
    ]
