# Generated by Codex on 2026-04-12

import decimal
import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organisations', '0007_rename_tenant_data_organis_d368f1_idx_tenant_data_organis_42bc8e_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='billing_gateway',
            field=models.CharField(blank=True, choices=[('MANUAL', 'Manual'), ('RAZORPAY', 'Razorpay'), ('STRIPE', 'Stripe')], max_length=20),
        ),
        migrations.AddField(
            model_name='organisationlicencebatch',
            name='gateway_subscription_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='organisationbillingevent',
            name='provider',
            field=models.CharField(choices=[('MANUAL', 'Manual'), ('RAZORPAY', 'Razorpay'), ('STRIPE', 'Stripe')], max_length=20),
        ),
        migrations.AlterField(
            model_name='organisationlicencebatch',
            name='payment_provider',
            field=models.CharField(choices=[('MANUAL', 'Manual'), ('RAZORPAY', 'Razorpay'), ('STRIPE', 'Stripe')], default='MANUAL', max_length=20),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('gateway', models.CharField(choices=[('MANUAL', 'Manual'), ('RAZORPAY', 'Razorpay'), ('STRIPE', 'Stripe')], max_length=20)),
                ('gateway_order_id', models.CharField(max_length=200, unique=True)),
                ('gateway_payment_id', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], default='PENDING', max_length=20)),
                ('idempotency_key', models.CharField(max_length=160, unique=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('failure_reason', models.TextField(blank=True)),
                ('gateway_options', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('licence_batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='organisations.organisationlicencebatch')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='organisations.organisation')),
            ],
            options={
                'db_table': 'organisation_payments',
                'ordering': ['-created_at'],
                'indexes': [
                    models.Index(fields=['organisation', 'status'], name='organisatio_organis_848ffa_idx'),
                    models.Index(fields=['licence_batch', 'status'], name='organisatio_licence_fa7949_idx'),
                ],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('invoice_number', models.CharField(max_length=50, unique=True)),
                ('issue_date', models.DateField()),
                ('due_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('gst_amount', models.DecimalField(decimal_places=2, default=decimal.Decimal('0.00'), max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ISSUED', 'Issued'), ('PAID', 'Paid'), ('VOID', 'Void')], default='ISSUED', max_length=20)),
                ('storage_key', models.CharField(blank=True, max_length=500)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='organisations.organisation')),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='invoice', to='organisations.payment')),
            ],
            options={
                'db_table': 'organisation_invoices',
                'ordering': ['-issue_date', '-created_at'],
                'indexes': [
                    models.Index(fields=['organisation', 'status'], name='organisatio_organis_cb795c_idx'),
                ],
            },
        ),
    ]
