# Generated by Django 4.2.16 on 2026-04-01 11:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


def backfill_tax_and_bootstrap_admin_data(apps, schema_editor):
    Organisation = apps.get_model('organisations', 'Organisation')
    OrganisationAddress = apps.get_model('organisations', 'OrganisationAddress')
    OrganisationBootstrapAdmin = apps.get_model('organisations', 'OrganisationBootstrapAdmin')
    OrganisationLegalIdentifier = apps.get_model('organisations', 'OrganisationLegalIdentifier')
    OrganisationTaxRegistration = apps.get_model('organisations', 'OrganisationTaxRegistration')
    User = apps.get_model('accounts', 'User')

    for organisation in Organisation.objects.all():
        legal_identifier = None
        pan_number = (organisation.pan_number or '').strip().upper()
        if pan_number:
            legal_identifier, _ = OrganisationLegalIdentifier.objects.get_or_create(
                organisation=organisation,
                country_code=organisation.country_code or 'IN',
                identifier_type='PAN',
                identifier=pan_number,
                defaults={'is_primary': True},
            )
            if not legal_identifier.is_primary:
                legal_identifier.is_primary = True
                legal_identifier.save(update_fields=['is_primary', 'updated_at'])

        bootstrap_email = (organisation.email or '').strip().lower()
        invited_user = None
        status = 'DRAFT'
        invitation_sent_at = None
        accepted_at = None

        if organisation.primary_admin_user_id:
            invited_user = User.objects.filter(id=organisation.primary_admin_user_id).first()
            if invited_user:
                bootstrap_email = bootstrap_email or invited_user.email
                status = 'INVITE_ACCEPTED'
                accepted_at = organisation.activated_at or organisation.updated_at
                invitation_sent_at = organisation.paid_marked_at or organisation.created_at

        if bootstrap_email:
            first_name = (getattr(invited_user, 'first_name', '') or '').strip() or 'Organisation'
            last_name = (getattr(invited_user, 'last_name', '') or '').strip() or 'Admin'
            OrganisationBootstrapAdmin.objects.update_or_create(
                organisation=organisation,
                defaults={
                    'first_name': first_name,
                    'last_name': last_name,
                    'email': bootstrap_email,
                    'phone': (organisation.phone or '').strip(),
                    'status': status,
                    'invited_user': invited_user,
                    'invitation_sent_at': invitation_sent_at,
                    'accepted_at': accepted_at,
                },
            )

        for address in OrganisationAddress.objects.filter(organisation=organisation).exclude(gstin__isnull=True).exclude(gstin=''):
            registration, _ = OrganisationTaxRegistration.objects.get_or_create(
                organisation=organisation,
                country_code=address.country_code or organisation.country_code or 'IN',
                registration_type='GSTIN' if (address.country_code or organisation.country_code or 'IN') == 'IN' else 'OTHER',
                identifier=(address.gstin or '').strip().upper(),
                defaults={
                    'state_code': address.state_code or '',
                    'legal_identifier': legal_identifier if (address.country_code or organisation.country_code or 'IN') == 'IN' else None,
                    'is_primary_billing': address.address_type == 'BILLING',
                },
            )
            update_fields = []
            if registration.state_code != (address.state_code or ''):
                registration.state_code = address.state_code or ''
                update_fields.append('state_code')
            if registration.legal_identifier_id != getattr(legal_identifier, 'id', None) and registration.country_code == 'IN':
                registration.legal_identifier = legal_identifier
                update_fields.append('legal_identifier')
            should_be_primary_billing = address.address_type == 'BILLING'
            if registration.is_primary_billing != should_be_primary_billing:
                registration.is_primary_billing = should_be_primary_billing
                update_fields.append('is_primary_billing')
            if update_fields:
                update_fields.append('updated_at')
                registration.save(update_fields=update_fields)
            if address.tax_registration_id != registration.id:
                address.tax_registration = registration
                address.save(update_fields=['tax_registration', 'updated_at'])


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organisations', '0008_organisationaddress_country_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganisationLegalIdentifier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('country_code', models.CharField(default='IN', max_length=2)),
                ('identifier_type', models.CharField(choices=[('PAN', 'PAN'), ('EIN', 'EIN'), ('ABN', 'ABN'), ('UEN', 'UEN'), ('OTHER', 'Other')], max_length=20)),
                ('identifier', models.CharField(max_length=64)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legal_identifiers', to='organisations.organisation')),
            ],
            options={
                'db_table': 'organisation_legal_identifiers',
            },
        ),
        migrations.AlterField(
            model_name='organisationaddress',
            name='gstin',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.CreateModel(
            name='OrganisationTaxRegistration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('country_code', models.CharField(default='IN', max_length=2)),
                ('registration_type', models.CharField(choices=[('GSTIN', 'GSTIN'), ('VAT', 'VAT'), ('TRN', 'TRN'), ('GST_HST', 'GST/HST'), ('OTHER', 'Other')], max_length=20)),
                ('identifier', models.CharField(max_length=64)),
                ('state_code', models.CharField(blank=True, default='', max_length=16)),
                ('is_primary_billing', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('legal_identifier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tax_registrations', to='organisations.organisationlegalidentifier')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_registrations', to='organisations.organisation')),
            ],
            options={
                'db_table': 'organisation_tax_registrations',
            },
        ),
        migrations.CreateModel(
            name='OrganisationBootstrapAdmin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('INVITE_PENDING', 'Invite Pending'), ('INVITE_ACCEPTED', 'Invite Accepted')], default='DRAFT', max_length=20)),
                ('invitation_sent_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invited_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bootstrap_admin_assignments', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bootstrap_admin', to='organisations.organisation')),
            ],
            options={
                'db_table': 'organisation_bootstrap_admins',
            },
        ),
        migrations.AddField(
            model_name='organisationaddress',
            name='tax_registration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='addresses', to='organisations.organisationtaxregistration'),
        ),
        migrations.RunPython(backfill_tax_and_bootstrap_admin_data, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='organisationtaxregistration',
            constraint=models.UniqueConstraint(fields=('country_code', 'registration_type', 'identifier'), name='unique_tax_registration_globally'),
        ),
        migrations.AddConstraint(
            model_name='organisationtaxregistration',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary_billing', True)), fields=('organisation',), name='unique_primary_billing_tax_registration_per_org'),
        ),
        migrations.AddConstraint(
            model_name='organisationlegalidentifier',
            constraint=models.UniqueConstraint(fields=('country_code', 'identifier_type', 'identifier'), name='unique_legal_identifier_globally'),
        ),
        migrations.AddConstraint(
            model_name='organisationlegalidentifier',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('organisation', 'identifier_type'), name='unique_primary_legal_identifier_per_org_type'),
        ),
    ]
