# Generated by Django 4.2.16 on 2026-04-01 15:26

import re
import django.db.models.deletion
from django.db import migrations, models


def normalize_phone_number(value):
    raw_value = (value or '').strip()
    if not raw_value:
        return ''
    cleaned = re.sub(r'[\s\-()]+', '', raw_value)
    if not cleaned.startswith('+'):
        return ''
    if not re.fullmatch(r'\+\d+', cleaned):
        return ''
    return cleaned


def backfill_bootstrap_admin_contacts(apps, schema_editor):
    EmailAddress = apps.get_model('accounts', 'EmailAddress')
    Person = apps.get_model('accounts', 'Person')
    PhoneNumber = apps.get_model('accounts', 'PhoneNumber')
    OrganisationBootstrapAdmin = apps.get_model('organisations', 'OrganisationBootstrapAdmin')

    for bootstrap_admin in OrganisationBootstrapAdmin.objects.select_related('invited_user', 'invited_user__person').all():
        normalized_email = (bootstrap_admin.email or '').strip().lower()
        normalized_phone = normalize_phone_number(bootstrap_admin.phone)

        resolved_person = getattr(bootstrap_admin.invited_user, 'person', None)
        email_record = None
        phone_record = None

        if normalized_email:
            email_record = EmailAddress.objects.filter(normalized_email=normalized_email).first()
            if email_record and resolved_person and email_record.person_id != resolved_person.id:
                continue
            if email_record:
                resolved_person = resolved_person or email_record.person

        if normalized_phone:
            phone_record = PhoneNumber.objects.filter(e164_number=normalized_phone).first()
            if phone_record and resolved_person and phone_record.person_id != resolved_person.id:
                phone_record = None
            elif phone_record:
                resolved_person = resolved_person or phone_record.person

        if resolved_person is None and (normalized_email or normalized_phone):
            resolved_person = Person.objects.create()

        if resolved_person and normalized_email and email_record is None:
            email_record = EmailAddress.objects.create(
                person=resolved_person,
                email=normalized_email,
                normalized_email=normalized_email,
                kind='WORK',
                is_primary=not resolved_person.email_addresses.filter(is_primary=True).exists(),
                is_login=True,
            )
        if resolved_person and normalized_phone and phone_record is None:
            phone_record = PhoneNumber.objects.create(
                person=resolved_person,
                e164_number=normalized_phone,
                display_number=bootstrap_admin.phone,
                kind='WORK',
                is_primary=not resolved_person.phone_numbers.filter(is_primary=True).exists(),
            )

        bootstrap_admin.email = normalized_email
        bootstrap_admin.phone = normalized_phone
        bootstrap_admin.person = resolved_person
        bootstrap_admin.email_address = email_record
        bootstrap_admin.phone_number = phone_record
        bootstrap_admin.save(
            update_fields=['email', 'phone', 'person', 'email_address', 'phone_number', 'updated_at']
        )


def noop(apps, schema_editor):
    return None


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_person_emailaddress_phonenumber_user_person'),
        ('organisations', '0009_organisationlegalidentifier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisationbootstrapadmin',
            name='email_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bootstrap_admin_profiles', to='accounts.emailaddress'),
        ),
        migrations.AddField(
            model_name='organisationbootstrapadmin',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bootstrap_admin_profiles', to='accounts.person'),
        ),
        migrations.AddField(
            model_name='organisationbootstrapadmin',
            name='phone_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bootstrap_admin_profiles', to='accounts.phonenumber'),
        ),
        migrations.RunPython(backfill_bootstrap_admin_contacts, noop),
    ]
