export type AccessScopeKind =
  | 'ALL_ORGANISATIONS'
  | 'SELECTED_ORGANISATIONS'
  | 'CURRENT_ORGANISATION'
  | 'ALL_EMPLOYEES'
  | 'OWN_RECORD'
  | 'REPORTING_TREE'
  | 'SELECTED_DEPARTMENTS'
  | 'SELECTED_OFFICE_LOCATIONS'
  | 'SELECTED_LEGAL_ENTITIES'
  | 'SELECTED_COST_CENTRES'
  | 'SELECTED_EMPLOYMENT_TYPES'
  | 'SELECTED_GRADES'
  | 'SELECTED_BANDS'
  | 'SELECTED_DESIGNATIONS'
  | 'SELECTED_EMPLOYEES'

export interface EffectiveScopeSummary {
  kind: AccessScopeKind
  label: string
}
