# Generated by Django 4.2.16 on 2026-04-01 17:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
        ('organisations', '0001_initial'),
        ('timeoff', '0001_initial'),
        ('locations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employees', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalStage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('sequence', models.PositiveIntegerField()),
                ('mode', models.CharField(choices=[('ALL', 'All approvers required'), ('ANY', 'Any approver can complete')], default='ALL', max_length=10)),
                ('fallback_type', models.CharField(choices=[('NONE', 'None'), ('SPECIFIC_EMPLOYEE', 'Specific Employee'), ('PRIMARY_ORG_ADMIN', 'Primary Organisation Admin')], default='NONE', max_length=24)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('fallback_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_stage_fallbacks', to='employees.employee')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'approval_stages',
                'ordering': ['sequence', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalWorkflow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_approval_workflows', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_workflows', to='organisations.organisation')),
            ],
            options={
                'db_table': 'approval_workflows',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalWorkflowRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('request_kind', models.CharField(choices=[('LEAVE', 'Leave'), ('ON_DUTY', 'On Duty')], max_length=20)),
                ('priority', models.PositiveIntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
                ('employment_type', models.CharField(blank=True, max_length=20)),
                ('designation', models.CharField(blank=True, max_length=255)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approval_rules', to='departments.department')),
                ('leave_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approval_rules', to='timeoff.leavetype')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('office_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approval_rules', to='locations.officelocation')),
                ('specific_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approval_rules', to='employees.employee')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='approvals.approvalworkflow')),
            ],
            options={
                'db_table': 'approval_workflow_rules',
                'ordering': ['priority', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalStageApprover',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('approver_type', models.CharField(choices=[('REPORTING_MANAGER', 'Reporting Manager'), ('SPECIFIC_EMPLOYEE', 'Specific Employee'), ('PRIMARY_ORG_ADMIN', 'Primary Organisation Admin')], max_length=24)),
                ('approver_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stage_approver_assignments', to='employees.employee')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvers', to='approvals.approvalstage')),
            ],
            options={
                'db_table': 'approval_stage_approvers',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='approvalstage',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='approvals.approvalworkflow'),
        ),
        migrations.CreateModel(
            name='ApprovalRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('request_kind', models.CharField(choices=[('LEAVE', 'Leave'), ('ON_DUTY', 'On Duty')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('current_stage_sequence', models.PositiveIntegerField(default=1)),
                ('subject_label', models.CharField(max_length=255)),
                ('object_id', models.UUIDField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_runs', to='organisations.organisation')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approval_runs', to='employees.employee')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='approvals.approvalworkflow')),
            ],
            options={
                'db_table': 'approval_runs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('SKIPPED', 'Skipped'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('comment', models.TextField(blank=True)),
                ('acted_at', models.DateTimeField(blank=True, null=True)),
                ('approval_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='approvals.approvalrun')),
                ('approver_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_approval_actions', to='employees.employee')),
                ('approver_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_actions', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='approvals.approvalstage')),
            ],
            options={
                'db_table': 'approval_actions',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='approvalstage',
            constraint=models.UniqueConstraint(fields=('workflow', 'sequence'), name='unique_stage_sequence_per_workflow'),
        ),
        migrations.AddIndex(
            model_name='approvalrun',
            index=models.Index(fields=['organisation', 'status'], name='approval_ru_organis_847feb_idx'),
        ),
        migrations.AddIndex(
            model_name='approvalrun',
            index=models.Index(fields=['content_type', 'object_id'], name='approval_ru_content_6b9d83_idx'),
        ),
        migrations.AddIndex(
            model_name='approvalaction',
            index=models.Index(fields=['approver_user', 'status'], name='approval_ac_approve_4a0729_idx'),
        ),
        migrations.AddIndex(
            model_name='approvalaction',
            index=models.Index(fields=['approval_run', 'status'], name='approval_ac_approva_8e96c0_idx'),
        ),
        migrations.AddConstraint(
            model_name='approvalaction',
            constraint=models.UniqueConstraint(fields=('approval_run', 'stage', 'approver_user'), name='unique_approval_action_per_user_stage'),
        ),
    ]
