# Generated by Django 4.2.16 on 2026-03-31 22:27

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0002_department_parent_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('SKIPPED', 'Skipped'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('comment', models.TextField(blank=True)),
                ('acted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'approval_actions',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_kind', models.CharField(choices=[('LEAVE', 'Leave'), ('ON_DUTY', 'On Duty')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('current_stage_sequence', models.PositiveIntegerField(default=1)),
                ('subject_label', models.CharField(max_length=255)),
                ('object_id', models.UUIDField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'approval_runs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalStage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('sequence', models.PositiveIntegerField()),
                ('mode', models.CharField(choices=[('ALL', 'All approvers required'), ('ANY', 'Any approver can complete')], default='ALL', max_length=10)),
                ('fallback_type', models.CharField(choices=[('NONE', 'None'), ('SPECIFIC_EMPLOYEE', 'Specific Employee'), ('PRIMARY_ORG_ADMIN', 'Primary Organisation Admin')], default='NONE', max_length=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'approval_stages',
                'ordering': ['sequence', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalStageApprover',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('approver_type', models.CharField(choices=[('REPORTING_MANAGER', 'Reporting Manager'), ('SPECIFIC_EMPLOYEE', 'Specific Employee'), ('PRIMARY_ORG_ADMIN', 'Primary Organisation Admin')], max_length=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'approval_stage_approvers',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalWorkflow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'approval_workflows',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalWorkflowRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('request_kind', models.CharField(choices=[('LEAVE', 'Leave'), ('ON_DUTY', 'On Duty')], max_length=20)),
                ('priority', models.PositiveIntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
                ('employment_type', models.CharField(blank=True, max_length=20)),
                ('designation', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approval_rules', to='departments.department')),
            ],
            options={
                'db_table': 'approval_workflow_rules',
                'ordering': ['priority', 'created_at'],
            },
        ),
    ]
