# Generated by Django 4.2.16 on 2026-03-31 22:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0006_employee_onboarding_completed_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('locations', '0002_officelocation_is_remote_and_more'),
        ('timeoff', '0001_initial'),
        ('approvals', '0001_initial'),
        ('organisations', '0006_backfill_addresses_and_locations'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalworkflowrule',
            name='leave_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approval_rules', to='timeoff.leavetype'),
        ),
        migrations.AddField(
            model_name='approvalworkflowrule',
            name='office_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approval_rules', to='locations.officelocation'),
        ),
        migrations.AddField(
            model_name='approvalworkflowrule',
            name='specific_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approval_rules', to='employees.employee'),
        ),
        migrations.AddField(
            model_name='approvalworkflowrule',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='approvals.approvalworkflow'),
        ),
        migrations.AddField(
            model_name='approvalworkflow',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_approval_workflows', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='approvalworkflow',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_workflows', to='organisations.organisation'),
        ),
        migrations.AddField(
            model_name='approvalstageapprover',
            name='approver_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stage_approver_assignments', to='employees.employee'),
        ),
        migrations.AddField(
            model_name='approvalstageapprover',
            name='stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvers', to='approvals.approvalstage'),
        ),
        migrations.AddField(
            model_name='approvalstage',
            name='fallback_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_stage_fallbacks', to='employees.employee'),
        ),
        migrations.AddField(
            model_name='approvalstage',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='approvals.approvalworkflow'),
        ),
        migrations.AddField(
            model_name='approvalrun',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='approvalrun',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_runs', to='organisations.organisation'),
        ),
        migrations.AddField(
            model_name='approvalrun',
            name='requested_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approval_runs', to='employees.employee'),
        ),
        migrations.AddField(
            model_name='approvalrun',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='approvals.approvalworkflow'),
        ),
        migrations.AddField(
            model_name='approvalaction',
            name='approval_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='approvals.approvalrun'),
        ),
        migrations.AddField(
            model_name='approvalaction',
            name='approver_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_approval_actions', to='employees.employee'),
        ),
        migrations.AddField(
            model_name='approvalaction',
            name='approver_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_actions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='approvalaction',
            name='stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='approvals.approvalstage'),
        ),
        migrations.AddConstraint(
            model_name='approvalstage',
            constraint=models.UniqueConstraint(fields=('workflow', 'sequence'), name='unique_stage_sequence_per_workflow'),
        ),
        migrations.AddConstraint(
            model_name='approvalaction',
            constraint=models.UniqueConstraint(fields=('approval_run', 'stage', 'approver_user'), name='unique_approval_action_per_user_stage'),
        ),
    ]
