# Generated by Django 4.2.16 on 2026-04-02 00:00

from django.db import migrations, models
import django.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalworkflow',
            name='default_request_kind',
            field=models.CharField(
                blank=True,
                choices=[
                    ('LEAVE', 'Leave'),
                    ('ON_DUTY', 'On Duty'),
                    ('ATTENDANCE_REGULARIZATION', 'Attendance Regularization'),
                ],
                max_length=32,
                null=True,
            ),
        ),
        migrations.AddConstraint(
            model_name='approvalworkflow',
            constraint=models.UniqueConstraint(
                condition=django.db.models.Q(('default_request_kind__isnull', False), ('is_default', True)),
                fields=('organisation', 'default_request_kind'),
                name='unique_default_approval_workflow_per_request_kind',
            ),
        ),
    ]
