# Generated by Django 4.2.16 on 2026-04-02 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0002_approvalworkflow_default_request_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalrun',
            name='request_kind',
            field=models.CharField(
                choices=[
                    ('LEAVE', 'Leave'),
                    ('ON_DUTY', 'On Duty'),
                    ('ATTENDANCE_REGULARIZATION', 'Attendance Regularization'),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name='approvalworkflowrule',
            name='request_kind',
            field=models.CharField(
                choices=[
                    ('LEAVE', 'Leave'),
                    ('ON_DUTY', 'On Duty'),
                    ('ATTENDANCE_REGULARIZATION', 'Attendance Regularization'),
                ],
                max_length=32,
            ),
        ),
    ]
