# Generated by Django 4.2.16 on 2026-04-01 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0002_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='approvalaction',
            index=models.Index(fields=['approver_user', 'status'], name='approval_ac_approve_4a0729_idx'),
        ),
        migrations.AddIndex(
            model_name='approvalaction',
            index=models.Index(fields=['approval_run', 'status'], name='approval_ac_approva_8e96c0_idx'),
        ),
        migrations.AddIndex(
            model_name='approvalrun',
            index=models.Index(fields=['organisation', 'status'], name='approval_ru_organis_847feb_idx'),
        ),
        migrations.AddIndex(
            model_name='approvalrun',
            index=models.Index(fields=['content_type', 'object_id'], name='approval_ru_content_6b9d83_idx'),
        ),
    ]
