# Generated by Django 4.2.16 on 2026-04-07 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0005_approval_governance'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='approvalworkflow',
            name='unique_default_approval_workflow_per_request_kind',
        ),
        migrations.RenameIndex(
            model_name='approvaldelegation',
            new_name='approval_de_organis_c918ba_idx',
            old_name='approval_de_organis_e47f0d_idx',
        ),
        migrations.RenameIndex(
            model_name='approvaldelegation',
            new_name='approval_de_delegat_0ed04e_idx',
            old_name='approval_de_delegat_38ebbe_idx',
        ),
        migrations.AddConstraint(
            model_name='approvalworkflow',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True), ('default_request_kind__isnull', False)), fields=('organisation', 'default_request_kind'), name='unique_default_approval_workflow_per_request_kind'),
        ),
    ]
