# Generated by Django 4.2.16 on 2026-04-10 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0006_remove_approvalworkflow_unique_default_approval_workflow_per_request_kind_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalrun',
            name='request_kind',
            field=models.CharField(choices=[('LEAVE', 'Leave'), ('ON_DUTY', 'On Duty'), ('ATTENDANCE_REGULARIZATION', 'Attendance Regularization'), ('PAYROLL_PROCESSING', 'Payroll Processing'), ('SALARY_REVISION', 'Salary Revision'), ('COMPENSATION_TEMPLATE_CHANGE', 'Compensation Template Change'), ('PROMOTION', 'Promotion'), ('TRANSFER', 'Transfer')], max_length=32),
        ),
        migrations.AlterField(
            model_name='approvalworkflow',
            name='default_request_kind',
            field=models.CharField(blank=True, choices=[('LEAVE', 'Leave'), ('ON_DUTY', 'On Duty'), ('ATTENDANCE_REGULARIZATION', 'Attendance Regularization'), ('PAYROLL_PROCESSING', 'Payroll Processing'), ('SALARY_REVISION', 'Salary Revision'), ('COMPENSATION_TEMPLATE_CHANGE', 'Compensation Template Change'), ('PROMOTION', 'Promotion'), ('TRANSFER', 'Transfer')], max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='approvalworkflowrule',
            name='request_kind',
            field=models.CharField(choices=[('LEAVE', 'Leave'), ('ON_DUTY', 'On Duty'), ('ATTENDANCE_REGULARIZATION', 'Attendance Regularization'), ('PAYROLL_PROCESSING', 'Payroll Processing'), ('SALARY_REVISION', 'Salary Revision'), ('COMPENSATION_TEMPLATE_CHANGE', 'Compensation Template Change'), ('PROMOTION', 'Promotion'), ('TRANSFER', 'Transfer')], max_length=32),
        ),
    ]
