# Generated by Django 4.2.16 on 2026-04-03 17:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payroll', '0008_payrollrunitem_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabourWelfareFundContribution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('min_wage', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('max_wage', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('employee_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('employer_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('applicable_months', models.JSONField(blank=True, default=list)),
                ('notes', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'db_table': 'labour_welfare_fund_contributions',
                'ordering': ['min_wage', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='LabourWelfareFundRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('country_code', models.CharField(default='IN', max_length=2)),
                ('state_code', models.CharField(max_length=16)),
                ('state_name', models.CharField(max_length=100)),
                ('wage_basis', models.CharField(choices=[('MONTHLY', 'Monthly'), ('HALF_YEARLY', 'Half Yearly'), ('ANNUAL', 'Annual')], default='MONTHLY', max_length=16)),
                ('deduction_frequency', models.CharField(choices=[('MONTHLY', 'Monthly'), ('HALF_YEARLY', 'Half Yearly'), ('ANNUAL', 'Annual')], default='HALF_YEARLY', max_length=16)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('source_label', models.CharField(blank=True, max_length=255)),
                ('source_url', models.URLField(blank=True, max_length=500)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'labour_welfare_fund_rules',
                'ordering': ['country_code', 'state_code', '-effective_from'],
            },
        ),
        migrations.CreateModel(
            name='ProfessionalTaxRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('country_code', models.CharField(default='IN', max_length=2)),
                ('state_code', models.CharField(max_length=16)),
                ('state_name', models.CharField(max_length=100)),
                ('income_basis', models.CharField(choices=[('MONTHLY', 'Monthly'), ('HALF_YEARLY', 'Half Yearly'), ('ANNUAL', 'Annual')], default='MONTHLY', max_length=16)),
                ('deduction_frequency', models.CharField(choices=[('MONTHLY', 'Monthly'), ('HALF_YEARLY', 'Half Yearly'), ('ANNUAL', 'Annual')], default='MONTHLY', max_length=16)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('source_label', models.CharField(blank=True, max_length=255)),
                ('source_url', models.URLField(blank=True, max_length=500)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'professional_tax_rules',
                'ordering': ['country_code', 'state_code', '-effective_from'],
            },
        ),
        migrations.CreateModel(
            name='ProfessionalTaxSlab',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('gender', models.CharField(choices=[('ANY', 'Any'), ('MALE', 'Male'), ('FEMALE', 'Female')], default='ANY', max_length=16)),
                ('min_income', models.DecimalField(decimal_places=2, max_digits=12)),
                ('max_income', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('deduction_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('applicable_months', models.JSONField(blank=True, default=list)),
                ('notes', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'db_table': 'professional_tax_slabs',
                'ordering': ['gender', 'min_income', 'created_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='arrears',
            new_name='payroll_arr_employe_e6e57b_idx',
            old_name='payroll_arr_employee_d27c71_idx',
        ),
        migrations.RenameIndex(
            model_name='investmentdeclaration',
            new_name='investment__employe_e9b7b4_idx',
            old_name='investment__employe_8eb3e8_idx',
        ),
        migrations.AddField(
            model_name='professionaltaxslab',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='professionaltaxslab',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='professionaltaxslab',
            name='rule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slabs', to='payroll.professionaltaxrule'),
        ),
        migrations.AddField(
            model_name='professionaltaxrule',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='professionaltaxrule',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='labourwelfarefundrule',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='labourwelfarefundrule',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='labourwelfarefundcontribution',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='labourwelfarefundcontribution',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='labourwelfarefundcontribution',
            name='rule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='payroll.labourwelfarefundrule'),
        ),
        migrations.AddConstraint(
            model_name='professionaltaxrule',
            constraint=models.UniqueConstraint(fields=('country_code', 'state_code', 'effective_from'), name='unique_professional_tax_rule_version'),
        ),
        migrations.AddConstraint(
            model_name='labourwelfarefundrule',
            constraint=models.UniqueConstraint(fields=('country_code', 'state_code', 'effective_from'), name='unique_labour_welfare_fund_rule_version'),
        ),
    ]
