# Generated by Django 4.2.16 on 2026-04-03 17:40

from decimal import Decimal

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('payroll', '0009_labourwelfarefundcontribution_labourwelfarefundrule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compensationassignment',
            name='is_pf_opted_out',
            field=models.BooleanField(default=False, help_text='Use only for eligible higher-wage new joiners whose EPF membership can be lawfully opted out.'),
        ),
        migrations.AddField(
            model_name='compensationassignment',
            name='vpf_rate_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('12.00'), help_text='Employee-side PF deduction rate. Use values above 12% to represent VPF.', max_digits=5),
        ),
    ]
