# Generated by Django 4.2.16 on 2026-04-03 17:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('payroll', '0010_compensationassignment_is_pf_opted_out_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payslip',
            name='esi_contribution_period_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payslip',
            name='esi_contribution_period_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payslip',
            name='esi_eligibility_mode',
            field=models.CharField(choices=[('NONE', 'None'), ('DIRECT', 'Direct Eligibility'), ('CONTINUED', 'Continued For Contribution Period')], default='NONE', max_length=16),
        ),
    ]
