# Generated by Django 4.2.16 on 2026-04-07 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0014_payrolltaxslabset_tax_category'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='payrolltdschallan',
            new_name='payroll_tds_organis_1f41a5_idx',
            old_name='payroll_tds_organis_882124_idx',
        ),
        migrations.RenameIndex(
            model_name='payrolltdschallan',
            new_name='payroll_tds_organis_3020c4_idx',
            old_name='payroll_tds_organis_8b2777_idx',
        ),
        migrations.RenameIndex(
            model_name='statutoryfilingbatch',
            new_name='statutory_f_organis_3b446d_idx',
            old_name='statutory_f_org_id_5fad0a_idx',
        ),
        migrations.RenameIndex(
            model_name='statutoryfilingbatch',
            new_name='statutory_f_organis_bd343e_idx',
            old_name='statutory_f_org_id_0d474b_idx',
        ),
        migrations.RenameIndex(
            model_name='statutoryfilingbatch',
            new_name='statutory_f_organis_9a3b79_idx',
            old_name='statutory_f_org_id_e1fe70_idx',
        ),
        migrations.AddField(
            model_name='compensationassignment',
            name='is_epf_exempt',
            field=models.BooleanField(default=False, help_text='Explicitly mark employees who are not required to continue EPF membership despite a PF opt-out request.'),
        ),
    ]
