# Generated by Django 4.2.16 on 2026-04-07 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0016_comp_assignment_status_eff_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurchargeRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiscal_year', models.CharField(max_length=9)),
                ('tax_regime', models.CharField(choices=[('OLD', 'Old'), ('NEW', 'New')], max_length=10)),
                ('income_threshold', models.DecimalField(decimal_places=2, max_digits=14)),
                ('surcharge_rate_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('effective_from', models.DateField()),
            ],
            options={
                'db_table': 'payroll_surcharge_rules',
                'ordering': ['fiscal_year', 'tax_regime', 'income_threshold'],
                'unique_together': {('fiscal_year', 'tax_regime', 'income_threshold')},
            },
        ),
    ]
