# Generated by Django 4.2.16 on 2026-04-07 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0007_rename_tenant_data_organis_d368f1_idx_tenant_data_organis_42bc8e_idx_and_more'),
        ('payroll', '0017_add_surcharge_rule_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostCentre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('gl_code', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_centres', to='organisations.organisation')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='payroll.costcentre')),
            ],
            options={
                'db_table': 'payroll_cost_centres',
                'ordering': ['code'],
                'unique_together': {('organisation', 'code')},
            },
        ),
    ]
