# Generated by Django 4.2.16 on 2026-04-08 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0018_add_cost_centre_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='compensationassignmentline',
            name='cost_centre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignment_lines', to='payroll.costcentre'),
        ),
        migrations.AddField(
            model_name='compensationtemplateline',
            name='cost_centre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='template_lines', to='payroll.costcentre'),
        ),
    ]
