# Generated by Django 4.2.16 on 2026-04-10 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0019_add_cost_centre_to_lines'),
    ]

    operations = [
        migrations.AddField(
            model_name='statutoryfilingbatch',
            name='artifact_storage_backend',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='statutoryfilingbatch',
            name='artifact_storage_key',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='statutoryfilingbatch',
            name='artifact_uploaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
