from django.urls import path

from .views import (
    CtSurchargeRuleListView,
    OrgArrearsDetailView,
    OrgArrearsListCreateView,
    OrgCompensationAssignmentListCreateView,
    OrgCompensationAssignmentSubmitView,
    OrgCompensationTemplateDetailView,
    OrgCompensationTemplateListCreateView,
    OrgCompensationTemplateSubmitView,
    OrgCostCentreDetailView,
    OrgCostCentreListCreateView,
    OrgForm12BBBulkDownloadView,
    OrgFullAndFinalSettlementDetailView,
    OrgFullAndFinalSettlementListView,
    OrgInvestmentDeclarationDetailView,
    OrgInvestmentDeclarationListView,
    OrgPayrollRunCalculateView,
    OrgPayrollRunCalculationStatusView,
    OrgPayrollRunDetailView,
    OrgPayrollRunFinalizeView,
    OrgPayrollRunForm16View,
    OrgPayrollRunItemListView,
    OrgPayrollRunListCreateView,
    OrgPayrollRunRerunView,
    OrgPayrollRunSubmitView,
    OrgPayrollStatutoryMasterListView,
    OrgPayrollSummaryView,
    OrgPayrollTaxSlabSetListCreateView,
    OrgPayrollTDSChallanDetailView,
    OrgPayrollTDSChallanListCreateView,
    OrgPayslipDownloadView,
    OrgStatutoryFilingBatchCancelView,
    OrgStatutoryFilingBatchDetailView,
    OrgStatutoryFilingBatchDownloadView,
    OrgStatutoryFilingBatchListCreateView,
    OrgStatutoryFilingBatchRegenerateView,
)

urlpatterns = [
    path(
        "payroll/summary/", OrgPayrollSummaryView.as_view(), name="org-payroll-summary"
    ),
    path(
        "payroll/statutory-masters/",
        OrgPayrollStatutoryMasterListView.as_view(),
        name="org-payroll-statutory-master-list",
    ),
    path(
        "payroll/surcharge-rules/",
        CtSurchargeRuleListView.as_view(),
        name="payroll-surcharge-rules-list",
    ),
    path(
        "payroll/cost-centres/",
        OrgCostCentreListCreateView.as_view(),
        name="payroll-cost-centre-list-create",
    ),
    path(
        "payroll/cost-centres/<uuid:cost_centre_id>/",
        OrgCostCentreDetailView.as_view(),
        name="payroll-cost-centre-detail",
    ),
    path(
        "payroll/tds-challans/",
        OrgPayrollTDSChallanListCreateView.as_view(),
        name="org-payroll-tds-challan-list-create",
    ),
    path(
        "payroll/tds-challans/<uuid:pk>/",
        OrgPayrollTDSChallanDetailView.as_view(),
        name="org-payroll-tds-challan-detail",
    ),
    path(
        "payroll/tax-slab-sets/",
        OrgPayrollTaxSlabSetListCreateView.as_view(),
        name="org-payroll-tax-slab-set-list",
    ),
    path(
        "payroll/templates/",
        OrgCompensationTemplateListCreateView.as_view(),
        name="org-compensation-template-list-create",
    ),
    path(
        "payroll/templates/<uuid:pk>/",
        OrgCompensationTemplateDetailView.as_view(),
        name="org-compensation-template-detail",
    ),
    path(
        "payroll/templates/<uuid:pk>/submit/",
        OrgCompensationTemplateSubmitView.as_view(),
        name="org-compensation-template-submit",
    ),
    path(
        "payroll/compensations/",
        OrgCompensationAssignmentListCreateView.as_view(),
        name="org-compensation-assignment-list-create",
    ),
    path(
        "payroll/compensations/<uuid:pk>/submit/",
        OrgCompensationAssignmentSubmitView.as_view(),
        name="org-compensation-assignment-submit",
    ),
    path(
        "payroll/full-and-final-settlements/",
        OrgFullAndFinalSettlementListView.as_view(),
        name="org-full-and-final-settlement-list",
    ),
    path(
        "payroll/full-and-final-settlements/<uuid:pk>/",
        OrgFullAndFinalSettlementDetailView.as_view(),
        name="org-full-and-final-settlement-detail",
    ),
    path(
        "payroll/arrears/",
        OrgArrearsListCreateView.as_view(),
        name="org-payroll-arrears-list-create",
    ),
    path(
        "payroll/arrears/<uuid:pk>/",
        OrgArrearsDetailView.as_view(),
        name="org-payroll-arrears-detail",
    ),
    path(
        "payroll/runs/",
        OrgPayrollRunListCreateView.as_view(),
        name="org-payroll-run-list-create",
    ),
    path(
        "payroll/runs/<uuid:pk>/",
        OrgPayrollRunDetailView.as_view(),
        name="org-payroll-run-detail",
    ),
    path(
        "payroll/runs/<uuid:pk>/items/",
        OrgPayrollRunItemListView.as_view(),
        name="org-payroll-run-item-list",
    ),
    path(
        "payroll/runs/<uuid:pk>/form16/",
        OrgPayrollRunForm16View.as_view(),
        name="org-payroll-run-form16",
    ),
    path(
        "payroll/runs/<uuid:pk>/calculate/",
        OrgPayrollRunCalculateView.as_view(),
        name="org-payroll-run-calculate",
    ),
    path(
        "payroll/runs/<uuid:pk>/calculation-status/",
        OrgPayrollRunCalculationStatusView.as_view(),
        name="org-payroll-run-calculation-status",
    ),
    path(
        "payroll/runs/<uuid:pk>/submit/",
        OrgPayrollRunSubmitView.as_view(),
        name="org-payroll-run-submit",
    ),
    path(
        "payroll/runs/<uuid:pk>/finalize/",
        OrgPayrollRunFinalizeView.as_view(),
        name="org-payroll-run-finalize",
    ),
    path(
        "payroll/runs/<uuid:pk>/rerun/",
        OrgPayrollRunRerunView.as_view(),
        name="org-payroll-run-rerun",
    ),
    path(
        "payroll/filings/",
        OrgStatutoryFilingBatchListCreateView.as_view(),
        name="org-payroll-filing-list-create",
    ),
    path(
        "payroll/filings/<uuid:pk>/",
        OrgStatutoryFilingBatchDetailView.as_view(),
        name="org-payroll-filing-detail",
    ),
    path(
        "payroll/filings/<uuid:pk>/regenerate/",
        OrgStatutoryFilingBatchRegenerateView.as_view(),
        name="org-payroll-filing-regenerate",
    ),
    path(
        "payroll/filings/<uuid:pk>/cancel/",
        OrgStatutoryFilingBatchCancelView.as_view(),
        name="org-payroll-filing-cancel",
    ),
    path(
        "payroll/payslips/<uuid:pk>/download/",
        OrgPayslipDownloadView.as_view(),
        name="org-payslip-download",
    ),
    path(
        "payroll/filings/<uuid:pk>/download/",
        OrgStatutoryFilingBatchDownloadView.as_view(),
        name="org-payroll-filing-download",
    ),
    path(
        "payroll/form12bb/<str:fiscal_year>/download/",
        OrgForm12BBBulkDownloadView.as_view(),
        name="org-form12bb-download",
    ),
    path(
        "payroll/form-12bb/<str:fiscal_year>/download/",
        OrgForm12BBBulkDownloadView.as_view(),
        name="org-form-12bb-download",
    ),
    path(
        "payroll/investment-declarations/",
        OrgInvestmentDeclarationListView.as_view(),
        name="org-investment-declaration-list",
    ),
    path(
        "payroll/investment-declarations/<uuid:pk>/",
        OrgInvestmentDeclarationDetailView.as_view(),
        name="org-investment-declaration-detail",
    ),
]
