# Generated by Django 4.2.16 on 2026-03-31 06:08

from django.db import migrations, models


def populate_account_types(apps, schema_editor):
    User = apps.get_model('accounts', 'User')
    User.objects.filter(role='CONTROL_TOWER').update(account_type='CONTROL_TOWER')
    User.objects.exclude(role='CONTROL_TOWER').update(account_type='WORKFORCE')


def noop(apps, schema_editor):
    return None


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_passwordresettoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_type',
            field=models.CharField(choices=[('CONTROL_TOWER', 'Control Tower'), ('WORKFORCE', 'Workforce')], default='WORKFORCE', max_length=20),
        ),
        migrations.RunPython(populate_account_types, noop),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(fields=('email', 'account_type'), name='unique_email_per_account_type'),
        ),
    ]
