# Generated by Django 4.2.16 on 2026-04-01 15:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


def backfill_people_and_emails(apps, schema_editor):
    Person = apps.get_model('accounts', 'Person')
    EmailAddress = apps.get_model('accounts', 'EmailAddress')
    User = apps.get_model('accounts', 'User')

    for user in User.objects.all().order_by('created_at', 'id'):
        normalized_email = (user.email or '').strip().lower()
        if not normalized_email:
            continue

        email_record = EmailAddress.objects.filter(normalized_email=normalized_email).first()
        if email_record is None:
            person = Person.objects.create()
            email_record = EmailAddress.objects.create(
                person=person,
                email=normalized_email,
                normalized_email=normalized_email,
                kind='WORK',
                is_primary=True,
                is_login=True,
                is_verified=bool(user.is_active),
            )
        else:
            person = email_record.person
            if not email_record.is_primary:
                EmailAddress.objects.filter(person=person, is_primary=True).exclude(id=email_record.id).update(is_primary=False)
                email_record.is_primary = True
            if not email_record.is_login:
                email_record.is_login = True
            if email_record.email != normalized_email:
                email_record.email = normalized_email
            if email_record.is_primary or email_record.is_login:
                email_record.save(update_fields=['email', 'is_primary', 'is_login', 'updated_at'])

        user.email = normalized_email
        user.person_id = person.id
        user.save(update_fields=['email', 'person'])


def noop(apps, schema_editor):
    return None


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_account_type_alter_user_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'people',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailAddress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('normalized_email', models.CharField(max_length=254, unique=True)),
                ('kind', models.CharField(choices=[('WORK', 'Work'), ('PERSONAL', 'Personal'), ('LEGAL', 'Legal'), ('EMERGENCY', 'Emergency'), ('OTHER', 'Other')], default='WORK', max_length=20)),
                ('is_primary', models.BooleanField(default=False)),
                ('is_login', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_addresses', to='accounts.person')),
            ],
            options={
                'db_table': 'email_addresses',
                'ordering': ['-is_primary', 'email'],
            },
        ),
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('e164_number', models.CharField(max_length=20, unique=True)),
                ('display_number', models.CharField(blank=True, max_length=32)),
                ('kind', models.CharField(choices=[('WORK', 'Work'), ('PERSONAL', 'Personal'), ('LEGAL', 'Legal'), ('EMERGENCY', 'Emergency'), ('OTHER', 'Other')], default='WORK', max_length=20)),
                ('is_primary', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_numbers', to='accounts.person')),
            ],
            options={
                'db_table': 'phone_numbers',
                'ordering': ['-is_primary', 'e164_number'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounts', to='accounts.person'),
        ),
        migrations.RunPython(backfill_people_and_emails, noop),
        migrations.AddConstraint(
            model_name='emailaddress',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('person',), name='unique_primary_email_per_person'),
        ),
        migrations.AddConstraint(
            model_name='phonenumber',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('person',), name='unique_primary_phone_per_person'),
        ),
    ]
