# Generated by Django 4.2.16 on 2026-03-30 20:49

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='date_of_exit',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='reporting_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_reports', to='employees.employee'),
        ),
        migrations.CreateModel(
            name='EmployeeGovernmentId',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('id_type', models.CharField(choices=[('PAN', 'PAN'), ('AADHAAR', 'Aadhaar')], max_length=20)),
                ('identifier_encrypted', models.TextField(blank=True)),
                ('masked_identifier', models.CharField(blank=True, max_length=32)),
                ('name_on_id', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='government_ids', to='employees.employee')),
            ],
            options={
                'db_table': 'employee_government_ids',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeBankAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('account_holder_name', models.CharField(max_length=255)),
                ('bank_name', models.CharField(blank=True, max_length=255)),
                ('account_number_encrypted', models.TextField(blank=True)),
                ('masked_account_number', models.CharField(blank=True, max_length=32)),
                ('ifsc_encrypted', models.TextField(blank=True)),
                ('masked_ifsc', models.CharField(blank=True, max_length=24)),
                ('account_type', models.CharField(choices=[('SAVINGS', 'Savings'), ('CURRENT', 'Current'), ('SALARY', 'Salary')], default='SALARY', max_length=20)),
                ('branch_name', models.CharField(blank=True, max_length=255)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='employees.employee')),
            ],
            options={
                'db_table': 'employee_bank_accounts',
                'ordering': ['-is_primary', '-updated_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='employeegovernmentid',
            constraint=models.UniqueConstraint(fields=('employee', 'id_type'), name='unique_employee_government_id_type'),
        ),
        migrations.AddConstraint(
            model_name='employeebankaccount',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('employee',), name='unique_primary_bank_account_per_employee'),
        ),
    ]
