# Generated by Django 4.2.16 on 2026-04-02 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0002_approvalworkflow_default_request_kind'),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='attendance_regularization_approval_workflow',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='assigned_attendance_regularization_employees',
                to='approvals.approvalworkflow',
            ),
        ),
        migrations.AddField(
            model_name='employee',
            name='leave_approval_workflow',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='assigned_leave_employees',
                to='approvals.approvalworkflow',
            ),
        ),
        migrations.AddField(
            model_name='employee',
            name='on_duty_approval_workflow',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='assigned_on_duty_employees',
                to='approvals.approvalworkflow',
            ),
        ),
    ]
