# Generated by Django 4.2.16 on 2026-04-02 20:30

import uuid

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employees', '0002_employee_approval_workflows'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeOffboardingProcess',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='IN_PROGRESS', max_length=20)),
                ('exit_status', models.CharField(choices=[('INVITED', 'Invited'), ('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('RESIGNED', 'Resigned'), ('RETIRED', 'Retired'), ('TERMINATED', 'Terminated')], max_length=20)),
                ('date_of_exit', models.DateField()),
                ('exit_reason', models.CharField(blank=True, max_length=255)),
                ('exit_notes', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='offboarding_process', to='employees.employee')),
                ('initiated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_offboarding_processes', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_offboarding_processes', to='organisations.organisation')),
            ],
            options={
                'db_table': 'employee_offboarding_processes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeOffboardingTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('owner', models.CharField(choices=[('ORG_ADMIN', 'Org Admin'), ('MANAGER', 'Manager'), ('EMPLOYEE', 'Employee'), ('PAYROLL', 'Payroll'), ('IT', 'IT')], default='ORG_ADMIN', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('WAIVED', 'Waived')], default='PENDING', max_length=20)),
                ('note', models.TextField(blank=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('is_required', models.BooleanField(default=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_offboarding_tasks', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='employees.employeeoffboardingprocess')),
            ],
            options={
                'db_table': 'employee_offboarding_tasks',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='employeeoffboardingprocess',
            index=models.Index(fields=['organisation', 'status'], name='employee_off_organis_22a0ff_idx'),
        ),
        migrations.AddIndex(
            model_name='employeeoffboardingprocess',
            index=models.Index(fields=['employee', 'status'], name='employee_off_employe_0c59ff_idx'),
        ),
        migrations.AddConstraint(
            model_name='employeeoffboardingtask',
            constraint=models.UniqueConstraint(fields=('process', 'code'), name='unique_offboarding_task_code_per_process'),
        ),
    ]
