# Generated by Django 4.2.16 on 2026-03-31 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_alter_employee_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='employee',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('INVITED', 'Invited'), ('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('RESIGNED', 'Resigned'), ('RETIRED', 'Retired'), ('TERMINATED', 'Terminated')], default='INVITED', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.UniqueConstraint(condition=models.Q(('employee_code__isnull', False), models.Q(('employee_code', ''), _negated=True)), fields=('organisation', 'employee_code'), name='unique_employee_code_per_org_when_present'),
        ),
    ]
