# Generated by Codex on 2026-04-01

from django.db import migrations


def backfill_employee_statuses(apps, schema_editor):
    Employee = apps.get_model('employees', 'Employee')
    Employee.objects.filter(status='INACTIVE').update(status='RESIGNED')


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_alter_employee_unique_together_and_more'),
    ]

    operations = [
        migrations.RunPython(backfill_employee_statuses, noop_reverse),
    ]
