# Generated by Django 4.2.16 on 2026-03-31 22:27

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_backfill_employee_statuses'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='onboarding_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='onboarding_status',
            field=models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('BASIC_DETAILS_PENDING', 'Basic Details Pending'), ('DOCUMENTS_PENDING', 'Documents Pending'), ('COMPLETE', 'Complete')], default='NOT_STARTED', max_length=32),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='blood_type',
            field=models.CharField(blank=True, choices=[('A_POSITIVE', 'A+'), ('A_NEGATIVE', 'A-'), ('B_POSITIVE', 'B+'), ('B_NEGATIVE', 'B-'), ('AB_POSITIVE', 'AB+'), ('AB_NEGATIVE', 'AB-'), ('O_POSITIVE', 'O+'), ('O_NEGATIVE', 'O-'), ('UNKNOWN', 'Unknown')], max_length=20),
        ),
        migrations.CreateModel(
            name='EmployeeFamilyMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('relation', models.CharField(choices=[('SPOUSE', 'Spouse'), ('FATHER', 'Father'), ('MOTHER', 'Mother'), ('SON', 'Son'), ('DAUGHTER', 'Daughter'), ('BROTHER', 'Brother'), ('SISTER', 'Sister'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=20)),
                ('is_dependent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_members', to='employees.employee')),
            ],
            options={
                'db_table': 'employee_family_members',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeEmergencyContact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('relation', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('alternate_phone_number', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_contacts', to='employees.employee')),
            ],
            options={
                'db_table': 'employee_emergency_contacts',
                'ordering': ['-is_primary', 'full_name'],
            },
        ),
        migrations.AddConstraint(
            model_name='employeeemergencycontact',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('employee',), name='unique_primary_emergency_contact_per_employee'),
        ),
    ]
