# Generated by Django 4.2.16 on 2026-04-01 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_employee_onboarding_completed_at_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='employee',
            name='unique_employee_code_per_org_when_present',
        ),
        migrations.RemoveConstraint(
            model_name='employeebankaccount',
            name='unique_primary_bank_account_per_employee',
        ),
        migrations.RemoveConstraint(
            model_name='employeeemergencycontact',
            name='unique_primary_emergency_contact_per_employee',
        ),
        migrations.AddField(
            model_name='educationrecord',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='educationrecord',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employeebankaccount',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeebankaccount',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employeeemergencycontact',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeemergencycontact',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employeefamilymember',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeefamilymember',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='educationrecord',
            index=models.Index(fields=['employee', 'is_deleted'], name='education_r_employe_b5de25_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['organisation', 'status', 'is_deleted'], name='employees_organis_e2b941_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['user', 'organisation', 'is_deleted'], name='employees_user_id_3737ee_idx'),
        ),
        migrations.AddIndex(
            model_name='employeebankaccount',
            index=models.Index(fields=['employee', 'is_deleted'], name='employee_ba_employe_c04d28_idx'),
        ),
        migrations.AddIndex(
            model_name='employeeemergencycontact',
            index=models.Index(fields=['employee', 'is_deleted'], name='employee_em_employe_a2a726_idx'),
        ),
        migrations.AddIndex(
            model_name='employeefamilymember',
            index=models.Index(fields=['employee', 'is_deleted'], name='employee_fa_employe_92a316_idx'),
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.UniqueConstraint(condition=models.Q(('employee_code__isnull', False), models.Q(('employee_code', ''), _negated=True), ('is_deleted', False)), fields=('organisation', 'employee_code'), name='unique_employee_code_per_org_when_present'),
        ),
        migrations.AddConstraint(
            model_name='employeebankaccount',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True), ('is_deleted', False)), fields=('employee',), name='unique_primary_bank_account_per_employee'),
        ),
        migrations.AddConstraint(
            model_name='employeeemergencycontact',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True), ('is_deleted', False)), fields=('employee',), name='unique_primary_emergency_contact_per_employee'),
        ),
    ]
