# Generated by Django 4.2.16 on 2026-04-07 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_employee_org_status_doj_index'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='employeeoffboardingprocess',
            new_name='employee_of_organis_335435_idx',
            old_name='employee_off_organis_22a0ff_idx',
        ),
        migrations.RenameIndex(
            model_name='employeeoffboardingprocess',
            new_name='employee_of_employe_1c04d7_idx',
            old_name='employee_off_employe_0c59ff_idx',
        ),
    ]
