# Generated by Codex on 2026-04-01

from django.db import migrations, models


def backfill_employee_profile_country_codes(apps, schema_editor):
    EmployeeProfile = apps.get_model('employees', 'EmployeeProfile')
    for profile in EmployeeProfile.objects.select_related('employee__organisation').all():
        updates = []
        target_country_code = getattr(profile.employee.organisation, 'country_code', None) or 'IN'
        if not profile.country_code:
            profile.country_code = target_country_code
            updates.append('country_code')
        if profile.state_code is None:
            profile.state_code = ''
            updates.append('state_code')
        if updates:
            profile.save(update_fields=updates)


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_remove_employee_unique_employee_code_per_org_when_present_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='country_code',
            field=models.CharField(blank=True, default='', max_length=2),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='state_code',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.RunPython(backfill_employee_profile_country_codes, migrations.RunPython.noop),
    ]
