# Generated by Django 4.2.16 on 2026-04-07 13:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organisations', '0007_rename_tenant_data_organis_d368f1_idx_tenant_data_organis_42bc8e_idx_and_more'),
        ('employees', '0007_rename_employee_off_organis_22a0ff_idx_employee_of_organis_335435_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomFieldDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('field_key', models.SlugField(help_text='API-safe key for this field (e.g., shirt_size, uniform_size)')),
                ('field_type', models.CharField(choices=[('TEXT', 'Text'), ('NUMBER', 'Number'), ('DATE', 'Date'), ('DROPDOWN', 'Dropdown'), ('CHECKBOX', 'Checkbox'), ('EMAIL', 'Email'), ('PHONE', 'Phone')], default='TEXT', max_length=20)),
                ('placement', models.CharField(choices=[('PERSONAL', 'Personal Info'), ('WORK', 'Work Info'), ('FAMILY', 'Family Info'), ('DOCUMENTS', 'Documents'), ('BANK', 'Bank Info'), ('CUSTOM', 'Custom')], default='CUSTOM', max_length=20)),
                ('is_required', models.BooleanField(default=False)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('dropdown_options', models.JSONField(blank=True, default=list, help_text='List of options for DROPDOWN type fields')),
                ('placeholder', models.CharField(blank=True, max_length=200)),
                ('help_text', models.CharField(blank=True, max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_field_definitions', to='organisations.organisation')),
            ],
            options={
                'db_table': 'custom_field_definitions',
                'ordering': ['placement', 'display_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='designation_ref',
            field=models.ForeignKey(blank=True, help_text='Reference to a Designation master entry', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees_with_designation', to='employees.employee'),
        ),
        migrations.CreateModel(
            name='CustomFieldValue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('value_text', models.TextField(blank=True)),
                ('value_number', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('value_date', models.DateField(blank=True, null=True)),
                ('value_boolean', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_field_values', to='employees.employee')),
                ('field_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='employees.customfielddefinition')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'custom_field_values',
            },
        ),
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('level', models.PositiveIntegerField(default=1, help_text='Hierarchy level (1 = highest, higher numbers = lower rank)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='designations', to='organisations.organisation')),
            ],
            options={
                'db_table': 'designations',
                'ordering': ['level', 'name'],
                'indexes': [models.Index(fields=['organisation', 'is_active'], name='designation_organis_25b13c_idx'), models.Index(fields=['organisation', 'level'], name='designation_organis_cfd3eb_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='designation',
            constraint=models.UniqueConstraint(fields=('organisation', 'name'), name='unique_designation_name_per_org'),
        ),
        migrations.AddIndex(
            model_name='customfieldvalue',
            index=models.Index(fields=['employee', 'is_deleted'], name='custom_fiel_employe_f797cb_idx'),
        ),
        migrations.AddConstraint(
            model_name='customfieldvalue',
            constraint=models.UniqueConstraint(fields=('employee', 'field_definition'), name='unique_custom_field_value_per_employee'),
        ),
        migrations.AddIndex(
            model_name='customfielddefinition',
            index=models.Index(fields=['organisation', 'is_active'], name='custom_fiel_organis_f75bae_idx'),
        ),
        migrations.AddIndex(
            model_name='customfielddefinition',
            index=models.Index(fields=['organisation', 'placement'], name='custom_fiel_organis_13592d_idx'),
        ),
        migrations.AddConstraint(
            model_name='customfielddefinition',
            constraint=models.UniqueConstraint(fields=('organisation', 'field_key'), name='unique_custom_field_key_per_org'),
        ),
    ]
