# Generated by Django 4.2.16 on 2026-04-07 13:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organisations', '0007_rename_tenant_data_organis_d368f1_idx_tenant_data_organis_42bc8e_idx_and_more'),
        ('employees', '0008_customfielddefinition_employee_designation_ref_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExitInterviewTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exit_interview_templates', to='organisations.organisation')),
            ],
            options={
                'db_table': 'exit_interview_templates',
                'ordering': ['name'],
                'unique_together': {('organisation', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ExitInterviewQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('question_text', models.TextField()),
                ('question_type', models.CharField(choices=[('RATING', 'Rating Scale'), ('TEXT', 'Free Text'), ('MULTIPLE_CHOICE', 'Multiple Choice'), ('YES_NO', 'Yes/No')], default='TEXT', max_length=20)),
                ('options', models.JSONField(blank=True, default=list)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_required', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='employees.exitinterviewtemplate')),
            ],
            options={
                'db_table': 'exit_interview_questions',
                'ordering': ['template', 'order'],
            },
        ),
        migrations.CreateModel(
            name='ExitInterview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('stage', models.CharField(choices=[('NOTICE_PERIOD', 'Notice Period'), ('LAST_DAY', 'Last Day'), ('EXIT', 'Exit'), ('AFTER_EXIT', 'After Exit')], default='EXIT', max_length=20)),
                ('scheduled_date', models.DateTimeField(blank=True, null=True)),
                ('conducted_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('overall_rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('conducted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conducted_exit_interviews', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exit_interviews', to='employees.employeeoffboardingprocess')),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exit_interviews', to='employees.exitinterviewtemplate')),
            ],
            options={
                'db_table': 'exit_interviews',
                'ordering': ['-scheduled_date'],
            },
        ),
        migrations.CreateModel(
            name='ExitInterviewResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('rating_value', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('text_value', models.TextField(blank=True)),
                ('choice_value', models.CharField(blank=True, max_length=255)),
                ('boolean_value', models.BooleanField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('exit_interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='employees.exitinterview')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='employees.exitinterviewquestion')),
            ],
            options={
                'db_table': 'exit_interview_responses',
                'unique_together': {('exit_interview', 'question')},
            },
        ),
    ]
