# Generated by Django 4.2.16 on 2026-04-10 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0008_alter_approvalrun_request_kind_and_more'),
        ('employees', '0010_add_transfer_promotion_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='expense_approval_workflow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_expense_employees', to='approvals.approvalworkflow'),
        ),
    ]
