# Generated by Django 4.2.16 on 2026-04-11 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0011_employee_expense_approval_workflow'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['organisation', 'reporting_to', 'status'], name='emp_org_mgr_status_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['organisation', 'department', 'status'], name='emp_org_dept_status_idx'),
        ),
    ]
