# Generated by Django 4.2.16 on 2026-03-31 22:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employees', '0006_employee_onboarding_completed_at_and_more'),
        ('documents', '0002_document_file_hash_document_reviewed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(max_length=60),
        ),
        migrations.CreateModel(
            name='OnboardingDocumentType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=60, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('IDENTITY_TAX', 'Identity & Tax'), ('ADDRESS', 'Address'), ('BANKING_PAYROLL', 'Banking & Payroll'), ('EDUCATION', 'Education'), ('PREVIOUS_EMPLOYMENT', 'Previous Employment'), ('STATUTORY_BENEFITS', 'Statutory Benefits'), ('FAMILY_NOMINEE', 'Family & Nominee'), ('MEDICAL_SAFETY', 'Medical & Safety'), ('POLICY_ACK', 'Policy Acknowledgement'), ('ROLE_COMPLIANCE', 'Role Compliance'), ('CUSTOM', 'Custom')], max_length=32)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_custom', models.BooleanField(default=False)),
                ('requires_identifier', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_onboarding_document_types', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'onboarding_document_types',
                'ordering': ['category', 'sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeDocumentRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_required', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('REQUESTED', 'Requested'), ('SUBMITTED', 'Submitted'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected'), ('WAIVED', 'Waived')], default='REQUESTED', max_length=20)),
                ('note', models.TextField(blank=True)),
                ('rejection_note', models.TextField(blank=True)),
                ('latest_uploaded_at', models.DateTimeField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_type_ref', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee_requests', to='documents.onboardingdocumenttype')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_requests', to='employees.employee')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_employee_documents', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_employee_document_requests', to=settings.AUTH_USER_MODEL)),
                ('waived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waived_employee_document_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'employee_document_requests',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='document',
            name='document_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='documents.employeedocumentrequest'),
        ),
        migrations.AddConstraint(
            model_name='employeedocumentrequest',
            constraint=models.UniqueConstraint(fields=('employee', 'document_type_ref'), name='unique_document_request_per_employee_type'),
        ),
    ]
