# Generated by Django 4.2.16 on 2026-04-01 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_document_version_alter_document_document_type_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='employeedocumentrequest',
            index=models.Index(fields=['employee', 'status'], name='employee_do_employe_125010_idx'),
        ),
    ]
