REPORT_DATASETS = {
    'employees': {
        'label': 'Employees',
        'description': 'Employee master data with department, location, manager, and employment status.',
        'base_model': 'employees.Employee',
        'default_date_field': 'date_of_joining',
        'fields': [
            {'code': 'employee.id', 'label': 'Employee ID', 'path': 'id', 'data_type': 'uuid', 'is_groupable': False},
            {'code': 'employee.employee_number', 'label': 'Employee Number', 'path': 'employee_code', 'data_type': 'string'},
            {'code': 'employee.full_name', 'label': 'Employee Name', 'path': 'user__email', 'data_type': 'string'},
            {'code': 'employee.status', 'label': 'Status', 'path': 'status', 'data_type': 'choice'},
            {'code': 'employee.date_of_joining', 'label': 'Date of Joining', 'path': 'date_of_joining', 'data_type': 'date'},
            {'code': 'department.name', 'label': 'Department', 'path': 'department__name', 'data_type': 'string'},
            {'code': 'office_location.name', 'label': 'Office Location', 'path': 'office_location__name', 'data_type': 'string'},
            {'code': 'employee.designation', 'label': 'Designation', 'path': 'designation', 'data_type': 'string'},
        ],
    },
    'payroll_runs': {
        'label': 'Payroll Runs',
        'description': 'Payroll run lines with employee, gross pay, deductions, and net pay.',
        'base_model': 'payroll.PayrollRunItem',
        'default_date_field': 'pay_run__created_at',
        'fields': [
            {'code': 'payroll.period_month', 'label': 'Payroll Month', 'path': 'pay_run__period_month', 'data_type': 'integer'},
            {'code': 'payroll.period_year', 'label': 'Payroll Year', 'path': 'pay_run__period_year', 'data_type': 'integer'},
            {'code': 'employee.employee_number', 'label': 'Employee Number', 'path': 'employee__employee_code', 'data_type': 'string'},
            {'code': 'employee.full_name', 'label': 'Employee Name', 'path': 'employee__user__email', 'data_type': 'string'},
            {
                'code': 'payroll.gross_pay',
                'label': 'Gross Pay',
                'path': 'gross_pay',
                'data_type': 'decimal',
                'is_summarizable': True,
                'is_sensitive': True,
                'permission_code': 'org.payroll.read',
            },
            {
                'code': 'payroll.net_pay',
                'label': 'Net Pay',
                'path': 'net_pay',
                'data_type': 'decimal',
                'is_summarizable': True,
                'is_sensitive': True,
                'permission_code': 'org.payroll.read',
            },
        ],
    },
    'leave_requests': {
        'label': 'Leave Requests',
        'description': 'Leave requests with employee, leave type, dates, and approval status.',
        'base_model': 'timeoff.LeaveRequest',
        'default_date_field': 'start_date',
        'fields': [
            {'code': 'leave.start_date', 'label': 'Start Date', 'path': 'start_date', 'data_type': 'date'},
            {'code': 'leave.end_date', 'label': 'End Date', 'path': 'end_date', 'data_type': 'date'},
            {'code': 'leave.status', 'label': 'Status', 'path': 'status', 'data_type': 'choice'},
            {'code': 'leave.type', 'label': 'Leave Type', 'path': 'leave_type__name', 'data_type': 'string'},
            {'code': 'employee.employee_number', 'label': 'Employee Number', 'path': 'employee__employee_code', 'data_type': 'string'},
            {'code': 'department.name', 'label': 'Department', 'path': 'employee__department__name', 'data_type': 'string'},
        ],
    },
}
