# Generated by Django 4.2.16 on 2026-03-31 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0005_organisation_pan_number_organisationaddress_and_more'),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='officelocation',
            name='is_remote',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='officelocation',
            name='organisation_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='office_locations', to='organisations.organisationaddress'),
        ),
    ]
