# Generated by Django 4.2.16 on 2026-03-31 22:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0006_employee_onboarding_completed_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('departments', '0002_department_parent_department'),
        ('locations', '0002_officelocation_is_remote_and_more'),
        ('organisations', '0006_backfill_addresses_and_locations'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('audience_type', models.CharField(choices=[('ALL_EMPLOYEES', 'All Employees'), ('DEPARTMENTS', 'Departments'), ('OFFICE_LOCATIONS', 'Office Locations'), ('SPECIFIC_EMPLOYEES', 'Specific Employees')], default='ALL_EMPLOYEES', max_length=30)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SCHEDULED', 'Scheduled'), ('PUBLISHED', 'Published'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=20)),
                ('scheduled_for', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_notices', to=settings.AUTH_USER_MODEL)),
                ('departments', models.ManyToManyField(blank=True, related_name='notices', to='departments.department')),
                ('employees', models.ManyToManyField(blank=True, related_name='notices', to='employees.employee')),
                ('office_locations', models.ManyToManyField(blank=True, related_name='notices', to='locations.officelocation')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notices', to='organisations.organisation')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_notices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notices',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
    ]
