# Generated by Django 4.2.16 on 2026-04-02 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notice',
            options={
                'db_table': 'notices',
                'ordering': ['-is_sticky', '-published_at', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='notice',
            name='category',
            field=models.CharField(
                choices=[
                    ('GENERAL', 'General'),
                    ('HR_POLICY', 'HR Policy'),
                    ('OPERATIONS', 'Operations'),
                    ('CELEBRATION', 'Celebration'),
                    ('COMPLIANCE', 'Compliance'),
                    ('URGENT', 'Urgent'),
                ],
                default='GENERAL',
                max_length=24,
            ),
        ),
        migrations.AddField(
            model_name='notice',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notice',
            name='is_sticky',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='notice',
            name='status',
            field=models.CharField(
                choices=[
                    ('DRAFT', 'Draft'),
                    ('SCHEDULED', 'Scheduled'),
                    ('PUBLISHED', 'Published'),
                    ('EXPIRED', 'Expired'),
                    ('ARCHIVED', 'Archived'),
                ],
                default='DRAFT',
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name='notice',
            index=models.Index(fields=['organisation', 'is_sticky', 'published_at'], name='notices_organis_5a5495_idx'),
        ),
    ]
