# Generated by Django 4.2.16 on 2026-04-01 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='notice',
            index=models.Index(fields=['organisation', 'status', 'published_at'], name='notices_organis_f93c31_idx'),
        ),
    ]
