# Generated by Django 4.2.16 on 2026-04-01 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeoff', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='leaverequest',
            index=models.Index(fields=['employee', 'status'], name='leave_reque_employe_fd03a1_idx'),
        ),
        migrations.AddIndex(
            model_name='leaverequest',
            index=models.Index(fields=['employee', 'start_date', 'end_date'], name='leave_reque_employe_dc8219_idx'),
        ),
        migrations.AddIndex(
            model_name='ondutyrequest',
            index=models.Index(fields=['employee', 'status'], name='on_duty_req_employe_d0cff6_idx'),
        ),
        migrations.AddIndex(
            model_name='ondutyrequest',
            index=models.Index(fields=['employee', 'start_date', 'end_date'], name='on_duty_req_employe_7ac0f0_idx'),
        ),
    ]
