# Generated by Django 4.2.16 on 2026-04-06 20:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_employeeprofile_statutory_ids'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('timeoff', '0002_add_leave_encashment'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompOffAccrual',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('accrual_date', models.DateField()),
                ('units', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('expires_on', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('REDEEMED', 'Redeemed'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'comp_off_accruals',
                'ordering': ['-accrual_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CompOffRedemption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('redemption_date', models.DateField()),
                ('units', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('REDEEMED', 'Redeemed'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('reason', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'comp_off_redemptions',
                'ordering': ['-redemption_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeaveWithoutPayEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('entry_date', models.DateField()),
                ('units', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('reason', models.TextField(blank=True)),
                ('source', models.CharField(choices=[('MANUAL', 'Manual'), ('ATTENDANCE', 'Attendance'), ('LEAVE_LAPSE', 'Leave Lapse'), ('PAYROLL', 'Payroll')], default='MANUAL', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'leave_without_pay_entries',
                'ordering': ['-entry_date', '-created_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='leaveencashmentrequest',
            new_name='leave_encas_employe_7cedec_idx',
            old_name='leave_encas_employee_4df4de_idx',
        ),
        migrations.RenameIndex(
            model_name='leaveencashmentrequest',
            new_name='leave_encas_employe_7a80b6_idx',
            old_name='leave_encas_employee_a213b0_idx',
        ),
        migrations.AddIndex(
            model_name='leaverequest',
            index=models.Index(fields=['employee', 'leave_type', 'status', 'start_date'], name='leave_req_balance_idx'),
        ),
        migrations.AddField(
            model_name='leavewithoutpayentry',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leavewithoutpayentry',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_without_pay_entries', to='employees.employee'),
        ),
        migrations.AddField(
            model_name='leavewithoutpayentry',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='compoffredemption',
            name='accrual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='redemptions', to='timeoff.compoffaccrual'),
        ),
        migrations.AddField(
            model_name='compoffredemption',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='compoffredemption',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comp_off_redemptions', to='employees.employee'),
        ),
        migrations.AddField(
            model_name='compoffredemption',
            name='leave_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comp_off_redemptions', to='timeoff.leaverequest'),
        ),
        migrations.AddField(
            model_name='compoffredemption',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='compoffaccrual',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='compoffaccrual',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comp_off_accruals', to='employees.employee'),
        ),
        migrations.AddField(
            model_name='compoffaccrual',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='leavewithoutpayentry',
            index=models.Index(fields=['employee', 'status'], name='leave_witho_employe_ac5e99_idx'),
        ),
        migrations.AddIndex(
            model_name='leavewithoutpayentry',
            index=models.Index(fields=['employee', 'entry_date'], name='leave_witho_employe_1d160e_idx'),
        ),
        migrations.AddIndex(
            model_name='compoffredemption',
            index=models.Index(fields=['employee', 'status'], name='comp_off_re_employe_b11e39_idx'),
        ),
        migrations.AddIndex(
            model_name='compoffredemption',
            index=models.Index(fields=['employee', 'redemption_date'], name='comp_off_re_employe_d918ea_idx'),
        ),
        migrations.AddIndex(
            model_name='compoffaccrual',
            index=models.Index(fields=['employee', 'status'], name='comp_off_ac_employe_498ab3_idx'),
        ),
        migrations.AddIndex(
            model_name='compoffaccrual',
            index=models.Index(fields=['employee', 'accrual_date'], name='comp_off_ac_employe_12ad4c_idx'),
        ),
    ]
