# Generated by Django 4.2.16 on 2026-04-03 18:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('locations', '0001_initial'),
        ('organisations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BiometricDevice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('device_serial', models.CharField(blank=True, help_text='Device serial number / SN', max_length=100)),
                ('protocol', models.CharField(choices=[('ZK_ADMS', 'ZKTeco / eSSL / Biomax (ADMS Push)'), ('MATRIX_COSEC', 'Matrix COSEC (REST Pull)'), ('SUPREMA_BIOSTAR', 'Suprema BioStar 2 (REST Pull)'), ('HIKVISION_ISAPI', 'HikVision ISAPI (REST Pull)')], max_length=30)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('port', models.PositiveIntegerField(default=80)),
                ('auth_username', models.CharField(blank=True, max_length=200)),
                ('api_key_hash', models.CharField(blank=True, help_text='SHA-256 hash of the device secret', max_length=128)),
                ('api_key_encrypted', models.TextField(blank=True)),
                ('oauth_client_id', models.CharField(blank=True, max_length=200)),
                ('oauth_client_secret_hash', models.CharField(blank=True, max_length=128)),
                ('oauth_client_secret_encrypted', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='biometric_devices', to='locations.officelocation')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biometric_devices', to='organisations.organisation')),
            ],
            options={
                'ordering': ['name', 'device_serial'],
            },
        ),
        migrations.CreateModel(
            name='BiometricSyncLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('synced_at', models.DateTimeField(auto_now_add=True)),
                ('records_fetched', models.PositiveIntegerField(default=0)),
                ('records_processed', models.PositiveIntegerField(default=0)),
                ('records_skipped', models.PositiveIntegerField(default=0)),
                ('errors', models.JSONField(blank=True, default=list)),
                ('success', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to='biometrics.biometricdevice')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-synced_at'],
            },
        ),
        migrations.AddIndex(
            model_name='biometricdevice',
            index=models.Index(fields=['organisation', 'protocol', 'is_active'], name='biometrics__organis_1b21d2_idx'),
        ),
        migrations.AddIndex(
            model_name='biometricdevice',
            index=models.Index(fields=['organisation', 'last_sync_at'], name='biometrics__organis_7f0903_idx'),
        ),
        migrations.AddConstraint(
            model_name='biometricdevice',
            constraint=models.UniqueConstraint(condition=~models.Q(('device_serial', '')), fields=('organisation', 'device_serial'), name='unique_biometric_device_serial_per_org'),
        ),
        migrations.AddIndex(
            model_name='biometricsynclog',
            index=models.Index(fields=['device', 'synced_at'], name='biometrics__device__ad7ec6_idx'),
        ),
    ]

