# Generated by Django 4.2.16 on 2026-04-07 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biometrics', '0002_add_essl_ebioserver_protocol'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='biometricdevice',
            new_name='biometrics__organis_490352_idx',
            old_name='biometrics__organis_1b21d2_idx',
        ),
        migrations.RenameIndex(
            model_name='biometricdevice',
            new_name='biometrics__organis_350246_idx',
            old_name='biometrics__organis_7f0903_idx',
        ),
        migrations.RenameIndex(
            model_name='biometricsynclog',
            new_name='biometrics__device__e0081c_idx',
            old_name='biometrics__device__ad7ec6_idx',
        ),
        migrations.AddField(
            model_name='biometricdevice',
            name='connectivity_mode',
            field=models.CharField(blank=True, choices=[('PUSH', 'Push (device-initiated)'), ('PULL', 'Pull (platform-initiated)'), ('EXPORT_BRIDGE', 'Export Bridge (batch/file)')], help_text='How the device communicates with Clarisal', max_length=20),
        ),
        migrations.AddField(
            model_name='biometricdevice',
            name='health_status',
            field=models.CharField(choices=[('UNKNOWN', 'Unknown'), ('HEALTHY', 'Healthy'), ('DEGRADED', 'Degraded'), ('FAILED', 'Failed')], default='UNKNOWN', max_length=20),
        ),
        migrations.AddField(
            model_name='biometricdevice',
            name='last_health_check_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='biometricdevice',
            name='product_family',
            field=models.CharField(blank=True, help_text='Product family or model series', max_length=100),
        ),
        migrations.AddField(
            model_name='biometricdevice',
            name='vendor',
            field=models.CharField(blank=True, choices=[('ZKTECO', 'ZKTeco'), ('ESSL', 'eSSL'), ('MATRIX', 'Matrix COSEC'), ('HIKVISION', 'HikVision'), ('SUPREMA', 'Suprema'), ('MANTRA', 'Mantra'), ('CP_PLUS', 'CP PLUS'), ('OTHER', 'Other / Unknown')], help_text='Vendor / manufacturer family', max_length=20),
        ),
        migrations.AlterField(
            model_name='biometricdevice',
            name='protocol',
            field=models.CharField(choices=[('ZK_ADMS', 'ZKTeco / eSSL / Biomax (ADMS Push)'), ('ESSL_EBIOSERVER', 'eSSL eBioserver (Webhook Push)'), ('MATRIX_COSEC', 'Matrix COSEC (REST Pull)'), ('SUPREMA_BIOSTAR', 'Suprema BioStar 2 (REST Pull)'), ('HIKVISION_ISAPI', 'HikVision ISAPI (REST Pull)'), ('MANTRA_AEBAS', 'Mantra / AEBAS Bridge'), ('CP_PLUS_EXPORT', 'CP PLUS Export Bridge')], max_length=30),
        ),
    ]
