from django.urls import path

from .views import (
    CtActAsCurrentView,
    CtActAsRefreshView,
    CtActAsStopView,
    CtBillingOverviewView,
    CTDashboardStatsView,
    CtOrganisationActAsStartView,
    CtOrganisationAdminDeactivateView,
    CtOrganisationAdminReactivateView,
    CtOrganisationAdminRevokePendingView,
    CtOrganisationAnalyticsView,
    CtOrganisationApprovalSupportView,
    CtOrganisationApprovalWorkflowDetailView,
    CtOrganisationApprovalWorkflowListCreateView,
    CtOrganisationAttendanceSupportView,
    CtOrganisationConfigurationView,
    CtOrganisationDataExportDetailView,
    CtOrganisationDataExportDownloadUrlView,
    CtOrganisationDataExportListCreateView,
    CtOrganisationDepartmentDeactivateView,
    CtOrganisationDepartmentDetailView,
    CtOrganisationDepartmentListCreateView,
    CtOrganisationEmployeeDetailView,
    CtOrganisationEmployeesView,
    CtOrganisationFeatureFlagsView,
    CtOrganisationHolidayCalendarDetailView,
    CtOrganisationHolidayCalendarListCreateView,
    CtOrganisationHolidayCalendarPublishView,
    CtOrganisationLeaveCycleDetailView,
    CtOrganisationLeaveCycleListCreateView,
    CtOrganisationLeavePlanDetailView,
    CtOrganisationLeavePlanListCreateView,
    CtOrganisationLocationDeactivateView,
    CtOrganisationLocationDetailView,
    CtOrganisationLocationListCreateView,
    CtOrganisationNotesView,
    CtOrganisationNoticeDetailView,
    CtOrganisationNoticeListCreateView,
    CtOrganisationNoticePublishView,
    CtOrganisationOnboardingChecklistView,
    CtOrganisationOnboardingProgressView,
    CtOrganisationOnboardingStepView,
    CtOrganisationOnboardingSupportView,
    CtOrganisationOnDutyPolicyDetailView,
    CtOrganisationOnDutyPolicyListCreateView,
    CtOrganisationPayrollSummaryView,
    CtOrganisationSeedMastersView,
    CtRazorpayWebhookView,
    OrganisationActivateView,
    OrganisationAddressDetailView,
    OrganisationAddressListCreateView,
    OrganisationAdminsView,
    OrganisationDetailView,
    OrganisationLicenceBatchDetailView,
    OrganisationLicenceBatchExtendExpiryView,
    OrganisationLicenceBatchListCreateView,
    OrganisationLicenceBatchMarkPaidView,
    OrganisationLicencesView,
    OrganisationListCreateView,
    OrganisationRestoreView,
    OrganisationSuspendView,
)

urlpatterns = [
    path('dashboard/', CTDashboardStatsView.as_view(), name='ct-dashboard'),
    path('billing/', CtBillingOverviewView.as_view(), name='ct-billing-overview'),
    path('billing/webhooks/razorpay/', CtRazorpayWebhookView.as_view(), name='ct-billing-webhook-razorpay'),
    path('act-as/', CtActAsCurrentView.as_view(), name='ct-act-as-current'),
    path('act-as/refresh/', CtActAsRefreshView.as_view(), name='ct-act-as-refresh'),
    path('act-as/stop/', CtActAsStopView.as_view(), name='ct-act-as-stop'),
    path('organisations/', OrganisationListCreateView.as_view(), name='organisation-list-create'),
    path('organisations/<uuid:pk>/', OrganisationDetailView.as_view(), name='organisation-detail'),
    path('organisations/<uuid:pk>/act-as/', CtOrganisationActAsStartView.as_view(), name='organisation-act-as-start'),
    path('organisations/<uuid:pk>/feature-flags/', CtOrganisationFeatureFlagsView.as_view(), name='organisation-feature-flags'),
    path('organisations/<uuid:pk>/activate/', OrganisationActivateView.as_view(), name='organisation-activate'),
    path('organisations/<uuid:pk>/restore/', OrganisationRestoreView.as_view(), name='organisation-restore'),
    path('organisations/<uuid:pk>/suspend/', OrganisationSuspendView.as_view(), name='organisation-suspend'),
    path('organisations/<uuid:pk>/licences/', OrganisationLicencesView.as_view(), name='organisation-licences'),
    path('organisations/<uuid:pk>/licence-batches/', OrganisationLicenceBatchListCreateView.as_view(), name='organisation-licence-batch-list-create'),
    path('organisations/<uuid:pk>/licence-batches/<uuid:batch_id>/', OrganisationLicenceBatchDetailView.as_view(), name='organisation-licence-batch-detail'),
    path('organisations/<uuid:pk>/licence-batches/<uuid:batch_id>/extend-expiry/', OrganisationLicenceBatchExtendExpiryView.as_view(), name='organisation-licence-batch-extend-expiry'),
    path('organisations/<uuid:pk>/licence-batches/<uuid:batch_id>/mark-paid/', OrganisationLicenceBatchMarkPaidView.as_view(), name='organisation-licence-batch-mark-paid'),
    path('organisations/<uuid:pk>/exports/', CtOrganisationDataExportListCreateView.as_view(), name='ct-organisation-data-export-list-create'),
    path('organisations/<uuid:pk>/exports/<uuid:export_id>/', CtOrganisationDataExportDetailView.as_view(), name='ct-organisation-data-export-detail'),
    path('organisations/<uuid:pk>/exports/<uuid:export_id>/download-url/', CtOrganisationDataExportDownloadUrlView.as_view(), name='ct-organisation-data-export-download-url'),
    path('organisations/<uuid:pk>/admins/', OrganisationAdminsView.as_view(), name='organisation-admins'),
    path('organisations/<uuid:pk>/admins/<uuid:admin_id>/deactivate/', CtOrganisationAdminDeactivateView.as_view(), name='ct-organisation-admin-deactivate'),
    path('organisations/<uuid:pk>/admins/<uuid:admin_id>/reactivate/', CtOrganisationAdminReactivateView.as_view(), name='ct-organisation-admin-reactivate'),
    path('organisations/<uuid:pk>/admins/<uuid:admin_id>/revoke-pending/', CtOrganisationAdminRevokePendingView.as_view(), name='ct-organisation-admin-revoke-pending'),
    path('organisations/<uuid:pk>/employees/', CtOrganisationEmployeesView.as_view(), name='ct-organisation-employees'),
    path('organisations/<uuid:pk>/employees/<uuid:employee_id>/', CtOrganisationEmployeeDetailView.as_view(), name='ct-organisation-employee-detail'),
    path('organisations/<uuid:pk>/attendance/', CtOrganisationAttendanceSupportView.as_view(), name='ct-organisation-attendance-support'),
    path('organisations/<uuid:pk>/analytics/', CtOrganisationAnalyticsView.as_view(), name='ct-organisation-analytics'),
    path('organisations/<uuid:pk>/onboarding-support/', CtOrganisationOnboardingSupportView.as_view(), name='ct-organisation-onboarding-support'),
    path('organisations/<uuid:pk>/onboarding-checklist/', CtOrganisationOnboardingChecklistView.as_view(), name='ct-organisation-onboarding-checklist'),
    path('organisations/<uuid:pk>/onboarding/', CtOrganisationOnboardingProgressView.as_view(), name='ct-organisation-onboarding-progress'),
    path('organisations/<uuid:pk>/onboarding/<str:step>/<str:action>/', CtOrganisationOnboardingStepView.as_view(), name='ct-organisation-onboarding-step'),
    path('organisations/<uuid:pk>/seed-masters/', CtOrganisationSeedMastersView.as_view(), name='ct-organisation-seed-masters'),
    path('organisations/<uuid:pk>/approvals/', CtOrganisationApprovalSupportView.as_view(), name='ct-organisation-approval-support'),
    path('organisations/<uuid:pk>/payroll/', CtOrganisationPayrollSummaryView.as_view(), name='ct-organisation-payroll-summary'),
    path('organisations/<uuid:pk>/holiday-calendars/', CtOrganisationHolidayCalendarListCreateView.as_view(), name='ct-organisation-holiday-calendar-list-create'),
    path('organisations/<uuid:pk>/holiday-calendars/<uuid:calendar_id>/', CtOrganisationHolidayCalendarDetailView.as_view(), name='ct-organisation-holiday-calendar-detail'),
    path('organisations/<uuid:pk>/holiday-calendars/<uuid:calendar_id>/publish/', CtOrganisationHolidayCalendarPublishView.as_view(), name='ct-organisation-holiday-calendar-publish'),
    path('organisations/<uuid:pk>/configuration/', CtOrganisationConfigurationView.as_view(), name='ct-organisation-configuration'),
    path('organisations/<uuid:pk>/locations/', CtOrganisationLocationListCreateView.as_view(), name='ct-organisation-location-list-create'),
    path('organisations/<uuid:pk>/locations/<uuid:location_id>/', CtOrganisationLocationDetailView.as_view(), name='ct-organisation-location-detail'),
    path('organisations/<uuid:pk>/locations/<uuid:location_id>/deactivate/', CtOrganisationLocationDeactivateView.as_view(), name='ct-organisation-location-deactivate'),
    path('organisations/<uuid:pk>/departments/', CtOrganisationDepartmentListCreateView.as_view(), name='ct-organisation-department-list-create'),
    path('organisations/<uuid:pk>/departments/<uuid:department_id>/', CtOrganisationDepartmentDetailView.as_view(), name='ct-organisation-department-detail'),
    path('organisations/<uuid:pk>/departments/<uuid:department_id>/deactivate/', CtOrganisationDepartmentDeactivateView.as_view(), name='ct-organisation-department-deactivate'),
    path('organisations/<uuid:pk>/leave-cycles/', CtOrganisationLeaveCycleListCreateView.as_view(), name='ct-organisation-leave-cycle-list-create'),
    path('organisations/<uuid:pk>/leave-cycles/<uuid:cycle_id>/', CtOrganisationLeaveCycleDetailView.as_view(), name='ct-organisation-leave-cycle-detail'),
    path('organisations/<uuid:pk>/leave-plans/', CtOrganisationLeavePlanListCreateView.as_view(), name='ct-organisation-leave-plan-list-create'),
    path('organisations/<uuid:pk>/leave-plans/<uuid:plan_id>/', CtOrganisationLeavePlanDetailView.as_view(), name='ct-organisation-leave-plan-detail'),
    path('organisations/<uuid:pk>/on-duty-policies/', CtOrganisationOnDutyPolicyListCreateView.as_view(), name='ct-organisation-on-duty-policy-list-create'),
    path('organisations/<uuid:pk>/on-duty-policies/<uuid:policy_id>/', CtOrganisationOnDutyPolicyDetailView.as_view(), name='ct-organisation-on-duty-policy-detail'),
    path('organisations/<uuid:pk>/approval-workflows/', CtOrganisationApprovalWorkflowListCreateView.as_view(), name='ct-organisation-approval-workflow-list-create'),
    path('organisations/<uuid:pk>/approval-workflows/<uuid:workflow_id>/', CtOrganisationApprovalWorkflowDetailView.as_view(), name='ct-organisation-approval-workflow-detail'),
    path('organisations/<uuid:pk>/notices/', CtOrganisationNoticeListCreateView.as_view(), name='ct-organisation-notice-list-create'),
    path('organisations/<uuid:pk>/notices/<uuid:notice_id>/', CtOrganisationNoticeDetailView.as_view(), name='ct-organisation-notice-detail'),
    path('organisations/<uuid:pk>/notices/<uuid:notice_id>/publish/', CtOrganisationNoticePublishView.as_view(), name='ct-organisation-notice-publish'),
    path('organisations/<uuid:pk>/notes/', CtOrganisationNotesView.as_view(), name='ct-organisation-notes'),
    path('organisations/<uuid:pk>/addresses/', OrganisationAddressListCreateView.as_view(), name='organisation-address-list-create'),
    path('organisations/<uuid:pk>/addresses/<uuid:address_id>/', OrganisationAddressDetailView.as_view(), name='organisation-address-detail'),
]
